### ISSUE TITLE
Use python's builtin abstract base classes

### ISSUE THREAD

**Issue by nikochiko** [codezonediitj/pydatastructs#100]
#### Description of the problem
The current code creates a new abstract class, as in the example below. Python has dedicated `abc.ABC`s for abstract base classes. It would provide us more flexibility and conform better to python's standards.

#### Example of the problem
https://github.com/codezonediitj/pydatastructs/blob/master/pydatastructs/linear_data_structures/arrays.py

#### References/Other comments
https://docs.python.org/3/library/abc.html
https://www.python.org/dev/peps/pep-3119/

**Comment by czgdp1807** [comment]
What will happen to if we will do this? Will there be any enhancement in code readability or software design?
Any comments @codezonediitj/gssoc2020 @codezonediitj/maintainers

**Comment by nikochiko** [comment]
Yes,
for example, arrays are `Sequence`s, with the [corresponding ABCs](https://docs.python.org/3/library/collections.abc.html), we can easily check that the given array is a `Sequence` with 
```python
isinstance(obj, Sequence)
```

More importantly, the ABCs have some abstract methods, which provide a layout for the subclass. These abstract methods need to be present in the subclasses. For example, an `Iterator` ABC would have the abstract method `__iter__`.
Also as this is a python standard library, we can expect it to become the standard way of creating ABCs. Additionally any changes in the rest of the python package would be reflected in its implementation and we won't have the overhead to do that changes manually on our end.
So all in all, if we are going to work with ABCs, I feel using the built-in procedure would be a robust way to go on. 
What are your thoughts?

**Comment by czgdp1807** [comment]
So, it looks like that if you inherit an ABC then it will not allow you to instantiate a class object unless you override all the abstract methods of the base class which is kind of good but depends on the use case. If you never want to define, `__iter__` in the arrays as arrays are usually meant for traversing via indexing then inheriting a class with abstract method `__iter__` will be of no use. 
IMO, it would make writing code more difficult as we will be forced to implement some methods which we don't want to. Having template designs is good but then customising them for our needs becomes difficult. It's good in those places where a base class provides an interface which is completely used by all the subclasses. In our case there are some DS which don't inherit all the methods completely from the base classes.
Let's see what others have to say.

**Comment by czgdp1807** [comment]
It's just about making things complex and difficult to maintain. Closing for now. You can go to #254 and #255 for doing these kind of things. Thanks for your contributions.
