### ISSUE TITLE
Armstrong no

### ISSUE THREAD

**Issue by raksha009** [codezonediitj/pydatastructs#103]
Hi! I want to add code for armstrong number in this project. Plz assign this task to me as a gssoc'20 participant.

**Comment by raksha009** [comment]
We can include code for these type of questions in folder 1D array.

**Comment by czgdp1807** [comment]
Hi @raksha009 
Thanks for the issue. 
Our project doesn't aim to add problem specific algorithms/data structures. You can pick any one of the data structures given in the following links and propose an API for the same,

1. https://en.wikipedia.org/wiki/List_of_data_structures#Linear_data_structures
2. https://en.wikipedia.org/wiki/List_of_data_structures#Trees
3. https://en.wikipedia.org/wiki/List_of_data_structures#Graphs

Keep contributing!!
