### ISSUE TITLE
Adding general N dimensional arrays

### ISSUE THREAD

**Issue by raksha009** [codezonediitj/pydatastructs#104]
I want to add code for 2d array or matrices addition and subtraction. Plz assign this issue to me as a participant of GSSOC'20.

**Comment by czgdp1807** [comment]
Hi @raksha009 
Adding 2D array seems to be a nice idea. Please come up with an API for the same. You may refer, https://en.wikipedia.org/wiki/Matrix_(mathematics)
It would be better if we can add general N dimensional arrays supported row major order internally.

**Comment by czgdp1807** [comment]
We don't assign issues but you can keep working on it and make a PR whenever the design discussions are finalised. See our plan of action at https://github.com/codezonediitj/pydatastructs/wiki/Plan-of-Action-for-the-Projects

**Comment by czgdp1807** [comment]
Here's some API which you can think of improving.
There can be class `MultiDimensionalArray` with the following data members and methods,
**Data Members**
1. `_ndim` - The number of dimensions in the array.
2. `_data` - The python list which will store the data in row major order.
3. `_dtype` - The data type of the elements.

**Methods**
1. `__new__(cls, dtype=NoneType, *args, **kwargs)`
2. `__getitem__(self, *indices)`
3. `__setitem__(self, value, *indices)`
4. `fill(self, elem)`

ping @codezonediitj/gssoc2020 Please help @raksha009 out further and suggest improvements on the above API for n dimensional arrays.
Thanks.

**Comment by raksha009** [comment]
Okk sure. I'll come up with the code asap. Plz assign me this issue.

**Comment by robotjellyzone** [comment]
Hi @raksha009 are working on it? Just asking to confirm and if you are stuck at any point then feel free to ask us.

**Comment by raksha009** [comment]
Yepp, was just learning about creating PRs and all. But I have started working on this issue. Sorry for the delay.
@robotjellyzone

**Comment by raksha009** [comment]
@robotjellyzone I am facing many issues. How to reach you on slack !?

**Comment by robotjellyzone** [comment]
Hi @raksha009 you can ask with anyone on the pydatastructs channel, every mentor will be more than happy to help. Do make sure that you use public channel of pydatastructs  to ask your queries rather than DMs as mentors are almost available everytime on public channels, not on DMs. :)

**Comment by raksha009** [comment]
Ohkk, thanks

**Comment by czgdp1807** [comment]
> @robotjellyzone I am facing many issues. How to reach you on slack !?

Feel free to describe your problems in the comments of this issue. It will help others facing similar problems.

**Comment by kichloo** [comment]
@czgdp1807 Can I work on this issue?

**Comment by czgdp1807** [comment]
@raksha009 Are you still working on this issue? Please let us know.

**Comment by JeanPierreMR** [comment]
Hello, retaking this problem (gonna work on it)
I could make a class that works as an array of arrays, so instead of this
__getitem__(self, *indices)
__setitem__(self, value, *indices)
which would mean that you have to call for the item like this
`list[1,4,5]`
you could call it like this 
`list[1][4][5]`
I feel that's the popular and most understandable way

**Comment by czgdp1807** [comment]
Well, internally a 1D list should be used.
