### ISSUE TITLE
Add Cartesian tree

### ISSUE THREAD

**Issue by ajaynair710** [codezonediitj/pydatastructs#106]

**Comment by czgdp1807** [comment]
Thanks.
Are you participating through GSSoC, 2020?
For further steps, please come up with an API design for Cartesian tree

**Comment by ajaynair710** [comment]
Yes, I am participating in GSSoC

**Comment by Disha5harma** [comment]
@czgdp1807 Is this issue still available?

**Comment by czgdp1807** [comment]
Yes. Please start by API design and comment it below.

**Comment by Disha5harma** [comment]
Can you please tell me what we have to do in API design? Like in PR we have
to add code only right? Actually I am new to open source contribution,
please help.

**Comment by czgdp1807** [comment]
> Can you please tell me what we have to do in API design?
In API design you have to find an appropriate class prototype. It is basically how you call functions or methods of a class. See, https://github.com/codezonediitj/pydatastructs/issues/142#issue-579958924 for API design of disjoint set data structure. Something similar is to be done for Cartesian trees.

**Comment by Disha5harma** [comment]
Okay,I will do it.Thanks.

**Comment by Disha5harma** [comment]
Following could be the API design for this problem-
`node`
This class  will represent the notion of cartesian tree with respect to the above data structure.
**Attributes** 
*data-stores any valid value 
*left-represents left child
*right-represents right child
`cartesian_tree`
 This class will create cartesian tree and perform operations 
**Attributes** 
*parent-to hold the index of parent of each number in the input array (**arr**) 
*leftchild-to hold the index of left-child of each number in the input array (**arr**)
*rightchild-to hold the index of right-child of each number in the input array (**arr**)
**Methods**
1.create_tree(arr)-for building the cartesian tree according to sequence
2.create_helper(root,arr,parent,leftchild,rightchild)-helper function to recursively create subtree under given root 
3.sort_using_cartesian(root)-helps to in sorting given arr using cartesian tree and priority queue
`PriorityQueue`
Implementing priority queue
**Attributes**
*data-valid value
*queue-list of data/pointers to data can be stored through this
*ele-valid data/pointers to data can be stored through this
**Methods**
*isEmpty-checks if the queue is empty
*insert(data)-inserts element in queue
*delete-pop function for queue 

Kindly check if this API design works.

**Comment by czgdp1807** [comment]
> `node`
> This class will represent the notion of cartesian tree with respect to the above data structure.
> **Attributes**
> 
> * data-stores any valid value
> * left-represents left child
> * right-represents right child

There is already a `TreeNode` class which can be used for the above purpose.



> `cartesian_tree`
> This class will create cartesian tree and perform operations
> **Attributes**
> 
> * parent-to hold the index of parent of each number in the input array (**arr**)
> * leftchild-to hold the index of left-child of each number in the input array (**arr**)
> * rightchild-to hold the index of right-child of each number in the input array (**arr**)
> 
> **Methods**
> 1.create_tree(arr)-for building the cartesian tree according to sequence
> 2.create_helper(root,arr,parent,leftchild,rightchild)-helper function to recursively create subtree under given root
> 3.sort_using_cartesian(root)-helps to in sorting given arr using cartesian tree and priority queue

Can we make these similar to the existing binary trees? Refer, https://github.com/codezonediitj/pydatastructs/blob/master/pydatastructs/trees/binary_trees.py



> `PriorityQueue`
> Implementing priority queue
> **Attributes**
> 
> * data-valid value
> * queue-list of data/pointers to data can be stored through this
> * ele-valid data/pointers to data can be stored through this
> 
> **Methods**
> 
> 1. isEmpty-checks if the queue is empty
> 2. insert(data)-inserts element in queue
> 3. delete-pop function for queue

See, https://github.com/codezonediitj/pydatastructs/pull/132#issuecomment-597229490

**Comment by Disha5harma** [comment]
> Can we make these similar to the existing binary trees? Refer, https://github.com/codezonediitj/pydatastructs/blob/master/pydatastructs/trees/binary_trees.py

Sir, I think all methods similar to this can't be implemented on this and for rest I am working.If I am wrong then pls guide.

**Comment by czgdp1807** [comment]
> Sir, I think all methods similar to this can't be implemented on cartesian tree and for rest I am working

I see. Can you make a PR for cartesian tree? We can figure out there which methods to reuse from the already existing code and which to keep from your patch.

**Comment by faizan2700** [comment]
@Disha5harma are you working on this issue? I want to participate in gsoc 2020 If no one is working on this I will submit API design. (it seems like this issue has not got any pr since 13 days or any comment therefore I am asking)

**Comment by czgdp1807** [comment]
@faizan2700 Our issue policy and PR policy allows you to work on this issue. API design has already been discussed above. You can directly go for a PR.
