### ISSUE TITLE
Adding `sort` method to heaps

### ISSUE THREAD

**Issue by ajaynair710** [codezonediitj/pydatastructs#107]

**Comment by czgdp1807** [comment]
It looks like this issue is quite problem specific. Which algorithm and data structure will be used to do this task?

**Comment by ajaynair710** [comment]
heap sort

**Comment by czgdp1807** [comment]
IMO, a `sort` function can be added in `BinaryHeap` for such tasks.

**Comment by Shweta0002** [comment]
Can I work on this?? Interested to participate in RGSoC.

**Comment by czgdp1807** [comment]
Hi, @Shweta0002 I would suggest to add a `sort` function in class `BinaryHeap` or in general for any heap in PyDataStructs. This function might return the nodes of the heap sorted. Please see the code for heaps at https://github.com/codezonediitj/pydatastructs/blob/master/pydatastructs/trees/heaps.py and find a suitable API for the method, `sort`.

**Comment by Shweta0002** [comment]
Oh ok ! But didn't get that API thing ?

**Comment by czgdp1807** [comment]
Basically API in the context of this issue means,  the prototype of the method `sort`. What arguments it should take, other than `self`(`BinaryHeap` object)?

**Comment by Shweta0002** [comment]
ok , so for now i have to add a heap sort function in heap file right?So I would like to do it , thanks.

**Comment by czgdp1807** [comment]
`sort` should be a member function of `Heap` class which can have different implementations in the child classes. You can proceed with a PR for this and rest of the things can be discussed there.

**Comment by nehasangeetajha** [comment]
can we have intro sort as one of the sorting techniques?
If yes can I try it?

**Comment by czgdp1807** [comment]
> intro sort

Can you please provide some reference to this sorting technique?

**Comment by nehasangeetajha** [comment]
@czgdp1807 Here's is it : 
https://en.wikipedia.org/wiki/Introsort

**Comment by czgdp1807** [comment]
We can add all the sorting algorithms in a file named, `algorithms` under `linear_data_structures`. The thing to consider is whether to add sequential version of such sorting algorithms or parallel ones. Optimized sequential sorting algorithms are pre-implemented in many languages/libraries. 
How can we make the introsort parallel? Any ideas?

**Comment by nehasangeetajha** [comment]
Can't say about introsort but would love to start with basic sorting techniques (making them parallel) if we can have this folder

**Comment by czgdp1807** [comment]
Yes we can have an `algorithms.py` file in `linear_data_structures`. Moreover, please let me know if you want your contributions to be counted as `gssoc20` or `rgsoc20`. AFAIK, the official working period for RGSoC, 2020 starts from around July. Before that you have to submit application for this project on RGSoC website before 31st March.

**Comment by nehasangeetajha** [comment]
Yes I am working on my application for RGSOC'20 for this project.  Till then, i want to contribute for GSSOC'20.

**Comment by HarsheetKakar** [comment]
> `sort` should be a member function of `Heap` class which can have different implementations in the child classes. You can proceed with a PR for this and rest of the things can be discussed there.

heapsort is in place sorting algorithm, how will we indicate user that the heap object cannot be used after sorting it? If it is not supposed to be in placed then we should probably take it out of the class and implement it separately.

**Comment by czgdp1807** [comment]
`heapsort` can be written as a function in `algorithms.py`. A max heap can be built using `BinaryHeap`. Exact algorithm is available at https://en.wikipedia.org/wiki/Heapsort (See pseudo code)

**Comment by HarsheetKakar** [comment]
> `heapsort` can be written as a function in `algorithms.py`. A max heap can be built using `BinaryHeap`. Exact algorithm is available at https://en.wikipedia.org/wiki/Heapsort (See pseudo code)

draft PR coming up
