### ISSUE TITLE
Add red-black tree

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#110]
#### References/Other comments
.. [1] https://en.wikipedia.org/wiki/Red%E2%80%93black_tree
.. [2] https://github.com/codezonediitj/pydatastructs/wiki/Plan-of-Action-for-the-Projects

**Comment by VibavariG** [comment]
I would like to work on this issue. I am a beginner and i have done red black trees in java. I would like to try this. Please assign me this issue. I am a participant of GSSoC '20

**Comment by czgdp1807** [comment]
Hi @VibavariG This issue is reserved for RGSoC, 2020. 
Please see [this list of GSSoC, 2020 issues](https://github.com/codezonediitj/pydatastructs/issues?q=is%3Aopen+is%3Aissue+label%3Agssoc20).

**Comment by nehasangeetajha** [comment]
I would like to work on this issue. I am participant for RGSOC'20 as well

**Comment by czgdp1807** [comment]
@nehasangeetajha Sure, you can start your work by coming up with an API design for red-black trees. Describe your design in the comments below.

**Comment by wowrao17** [comment]
Hey! I would love to contribute to the same. Can I just know if the code has to be in Python only? Or can I use C++ as well?

**Comment by czgdp1807** [comment]
Hi @wowrao17 If @nehasangeetajha doesn't come up with an API design for red-black for some days(may be 3 or 4) then feel free to start your work on this issue.
The code should be in Python only, however before jumping to implementation we will focus on design aspect. Let us know your queries/doubts.

**Comment by wowrao17** [comment]
Okay, Thank you :)

**Comment by nehasangeetajha** [comment]
I have come up with following API design for red black tree.
`node` class with following data members:
1. `data` - data stored in current node
2. `parent` - reference to parent of current node
3. `left` - reference to left child of current node
4. `right` - refernce to right child of current node
5. `color` - color(either red or black) of current node

**Red Black tree class** with following methods:
1. `insert` : Function to insert a new node in current tree
2. `delete` : Function to delete a node from the tree
3. `print` : Function to print the nodes of current red black tree
4. `get_root`: To get root of the tree
5. `left_rotate`
6. `right_rotate`
7. `maximum`
8. `minimum`
9. `predecessor`
10. `successor`
11. `postorder`
12. `preorder`
13. `inorder`
with some private helper functions as and when required.
Thank you.
Please suggest improvements if any so that i can start working on it

**Comment by czgdp1807** [comment]
> `node` class with following data members:
> 
> 1. `data` - data stored in current node
> 2. `parent` - reference to parent of current node
> 3. `left` - reference to left child of current node
> 4. `right` - refernce to right child of current node
> 5. `color` - color(either red or black) of current node

Can we extend the already existing `TreeNode` class and add `color` attribute to the subclass.



> 3\. `print` : Function to print the nodes of current red black tree

Use, `__str__` to stringify the red black trees.



> * `left_rotate`
> * `right_rotate`

Are these similar to the rotations in `AVLTree`?

> * `maximum`
> * `minimum`
> * `predecessor`
> * `successor`

What will  be the use of these methods?



> * `postorder`
> * `preorder`
> * `inorder`

These are already defined in `BinaryTreeTraversal` in `binary_trees.py`.

**Comment by HarsheetKakar** [comment]
@nehasangeetajha can i take over it or are u doing it?

**Comment by nehasangeetajha** [comment]
@HarsheetKakar u can take this over , i am working on another issue now

**Comment by HarsheetKakar** [comment]
The main problem I am facing with this particular issue is that since the implementation of tree is done with array, object chaining is very difficult. Something like `root.left.left` becomes `self.tree[self.tree[self.tree[root_idx].left].left]` so I am planning to add more properties in ArrayForTrees which might help with this project as well as those to come. All suggestions are welcome.

**Comment by HarsheetKakar** [comment]
> The main problem I am facing with this particular issue is that since the implementation of tree is done with array, object chaining is very difficult. Something like `root.left.left` becomes `self.tree[self.tree[self.tree[root_idx].left].left]` so I am planning to add more properties in ArrayForTrees which might help with this project as well as those to come. All suggestions are welcome.

shall I raise an issue for implementing properties helping object chaining without pointers?

**Comment by czgdp1807** [comment]
Why do we want to do object chaining? Where is this exactly needed?

**Comment by czgdp1807** [comment]
```cpp
Node* GetParent(Node* n) {
  // Note that parent is set to null for the root node.
  return n == nullptr ? nullptr : n->parent;
}

Node* GetGrandParent(Node* n) {
  // Note that it will return nullptr if this is root or child of root
  return GetParent(GetParent(n));
}

Node* GetSibling(Node* n) {
  Node* p = GetParent(n);

  // No parent means no sibling.
  if (p == nullptr) {
    return nullptr;
  }

  if (n == p->left) {
    return p->right;
  } else {
    return p->left;
  }
}

Node* GetUncle(Node* n) {
  Node* p = GetParent(n);

  // No parent means no uncle
  return GetSibling(p);
}
```
As far as I can figure out, we need to access the current node's either parent, grand parent or sibling. You may define these helper functions in python under `RedBlackTree` class and use them where ever needed.

**Comment by czgdp1807** [comment]
You should be able to avoid such `root.left.left` and such stuff as there doesn't appear to be any string having, `->left->` as substring in https://en.wikipedia.org/wiki/Red%E2%80%93black_tree
I hope you are getting my point.

**Comment by HarsheetKakar** [comment]
I get ur point. I think a function would also work. Lets try that too.

**Comment by MuskanPaliwal** [comment]
Hi, @czgdp1807 . This is Muskan from the team CodeUrs, participating in RGSoC 2020. We want to work on the issue. 
Here is an API design that we have come up with. 
- `RedBlackTreeNode` class will be an extension of the `TreeNode` class present in the Node file.

  -The `RedBlackTreeNode` will contain all the data members of the `TreeNode` class with an extra parameter **color bit** which will be 1 for Red Node and 0 for Black Node.
 
- `RedBlackTree` class will be created in `binary_trees.py` file.
  -The class will be inherited from the `SelfBalancingBinaryTree` class which is inherited from the `BinarySearchTree` class.

- Methods the class will support are:-
  -`fix_insertion` : will contain the standard binary search tree `insertion` method defined in `BinarySearchTree` class followed by the methods to fix the properties of RB Tree.

  -`fix_deletion` : will contain the standard binary search tree `deletion` method defined in `BinarySearchTree` class followed by the methods to fix the properties of RB Tree.

 - `search` : Already available in `BinarySearchTree` class.

 - Some helper function `Getparent`, `GetGrandParent`, `GetSibling`, `GetUncle` in `RedBlackTree` class.
 - Functions for rotation are l`eft_rotate`, `right_rotate`, `right_left_rotate`, `left_right_rotate` and are already available in the class `SelfBalancingBinaryTree` .

- `preorder`, `postorder`, `inorder` these traversal functions are also available in the class `BinaryTreeTraversal`.

**Comment by czgdp1807** [comment]
Looks good. `fix_insertion`->`insert`, `fix_deletion`->`delete`. Do not use camel case style for function naming, for example `Getparent`->`_get_parent`(helper functions should follow the naming style of private methods, see the underscore in the beginning). The methods proposed are good as of now, rest let's see the PR(it should follow the coding style, otherwise it will be difficult to review and may get ignored).

**Comment by MuskanPaliwal** [comment]
Yeah Okay. we are working on it and will raise PR by tomorrow morning.

**Comment by hemabhagnani** [comment]
Hi @czgdp1807  ,this is Hema Bhagnani, Can we use recursion in the `_fix_insert` function of `Redblacktree` class or we have to use iteration??

**Comment by czgdp1807** [comment]
Well, iteration is preferred over recursion due to the overhead costs involved in recursion.

**Comment by MuskanPaliwal** [comment]
We have written the code for deletion and insertion using iteration but the code is not looking good. I am just curious why iteration is preferred over recursion. It would be great if you could share some resources here for the topic. 
Also, we are not able to use the BST delete function in RB deletion this is because of the color property. Can't we create a new function for rb tree deletion?

**Comment by czgdp1807** [comment]
I cannot get how code is not looking good. 

> Recursion is usually much slower because all function calls must be stored in a stack to allow the return back to the caller functions. In many cases, memory has to be allocated and copied to implement scope isolation.



> Also, we are not able to use the BST delete function in RB deletion this is because of the color property. Can't we create a new function for rb tree deletion?

You can.
