### ISSUE TITLE
Add depth first search for graphs

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#111]
#### Description of the problem

Serial and Parallel version of depth first search are required to be added for graphs.
#### References/Other comments
.. [1] https://en.wikipedia.org/wiki/Depth-first_search
.. [2] https://research.nvidia.com/sites/default/files/publications/nvr-2017-001.pdf

It looks like its too costly to implement parallel DFS as the algorithm is inherently sequential.

**Comment by asaw4** [comment]
i would like to work on this problem. please assign me this problem

**Comment by czgdp1807** [comment]
Are you participating through GSSoC, 2020?

**Comment by kritika12298** [comment]
I would like to work on this problem, please assign me

**Comment by czgdp1807** [comment]
Hi, @kritika12298 
Feel free to start with the serial version of DFS. Please propose an API for the same(the function name, arguments for the function). I have proposed an API for BFS at https://github.com/codezonediitj/pydatastructs/issues/82#issuecomment-591010265 and https://github.com/codezonediitj/pydatastructs/issues/82#issuecomment-591253631
Something similar can be done for DFS as well. 
P.S. We don't assign issues to contributors, however, this doesn't mean that they are not allowed to work on that issue. We think a PR is more important than assigning issues, so whenever you do make a PR, the issue will be linked to that PR and you can keep working on it. 
Let us know in case you face problems/queries.

**Comment by kritika12298** [comment]
Okay thank you

**Comment by wowrao17** [comment]
Hello Sir! I would like to contribute to this project. As far as I have understood, proposing an API means writing the name of the function and its arguments. So, here I have made this function for the same:
1. addEdge(self,v,visited)   //for adding the edge
2. DFShelper(self, v, visited) // a helping function for the DFS function
3. DFS(self,v) // function for DFS traversal

These are the main functions. I have also written the entire code for this. If you want, I can share it as well. 
If something is misunderstood by me or needs any changes, please inform me.

**Comment by czgdp1807** [comment]
@wowrao17 The API for depth first search should be along the lines of breadth first search. See, https://github.com/codezonediitj/pydatastructs/blob/master/pydatastructs/graphs/algorithms.py
DFS cannot be made parallel due to its inherently sequential nature. There are some publications which claim to have made it parallel but it's too costly to implement their ideas.

**Comment by golashboy** [comment]
I would like to work on it.

**Comment by czgdp1807** [comment]
@golashboy You can work on it. Please go through https://github.com/codezonediitj/pydatastructs/wiki/Plan-of-Action-for-the-Projects to see the steps for adding any data structure or algorithm. The API for depth first search should be similar to https://github.com/codezonediitj/pydatastructs/blob/797ec26e210c82fb8459a947e28307c16016c951/pydatastructs/graphs/algorithms.py#L22-L23

**Comment by golashboy** [comment]
Ok thanks
