### ISSUE TITLE
Improve examples

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#112]
#### Description of the problem

In the following snippet,

https://github.com/codezonediitj/pydatastructs/blob/18524daaf177df0d1daa7fa93a8f66362487500b/pydatastructs/linear_data_structures/linked_lists.py#L39-L53

`print` has been used for showing string output, instead, `str` should have been used. Changes should be made in the above part of the code as well as such things should be checked in other parts of the codebase as well and a single PR should be made for such improvements.

**Comment by czgdp1807** [comment]
Some classes don't have examples. This can be done in a separate PR other than one doing the above fixes.

**Comment by iamrajiv** [comment]
@czgdp1807 changing `print()` with `str()` is giving `DocTestFailure`. For example `str()` is returning like this `'[7.2, 5]'`

**Comment by czgdp1807** [comment]
Yeah so you can make changes to the results by adding `'`.

**Comment by iamrajiv** [comment]
@czgdp1807 I have made changes to `linked_list.py` and other parts of the codebase is already changed like in `stack.py`, `binary_trees.py`, `heaps.py`, `space_partitioning_trees.py` and `queue.py` though there is no use of printing the queue list in `queue.py` so what about adding function to return the contents of queue?
