### ISSUE TITLE
Linked list implementation of stack and queue data structure

### ISSUE THREAD

**Issue by asaw4** [codezonediitj/pydatastructs#113]
kindly assign me this problem .

**Comment by czgdp1807** [comment]
Array implementation of stacks and queues have already been added. See, https://github.com/codezonediitj/pydatastructs/tree/master/pydatastructs/miscellaneous_data_structures
Feel free to add the linked list implementation of these two once, #99 is merged which will be done by tomorrow.

**Comment by abhishekgupta368** [comment]
can i contribute

**Comment by czgdp1807** [comment]
@abhishekgupta368 Sure, you can.  We allow only one PR to remain open for any issue. The best PR will be kept and rest others will be closed in its favour.  See our PR policy at https://github.com/codezonediitj/pydatastructs/wiki/Pull-Request-Policy

**Comment by czgdp1807** [comment]
Note that #99 will be merged by tomorrow after which you can start your work on linked list implementation of stacks and queues.

**Comment by HarsheetKakar** [comment]
Can I work on LinkedListStack implementation?

**Comment by nehasangeetajha** [comment]
Is this issue still available? If yes can I start working on this?

**Comment by HarsheetKakar** [comment]
waiting for #152 to be merged, queue is already implemented, stack on its way
