### ISSUE TITLE
Array implementation of doubly ended queue (deque)

### ISSUE THREAD

**Issue by anirudh-kac** [codezonediitj/pydatastructs#120]
#### Description of the problem
I propose the implementation of a doubly ended queue (deque) using arrays. A deque allows insertions and deletions from both the front and the rear end.  The various methods available will be insert front, insert rear, delete front , delete rear in addition to returning the element at front or rear.

Hope this task will be assigned to me

**Comment by czgdp1807** [comment]
Hi @anirudh-kac 
IMO, double ended queue can be added to [this file](https://github.com/codezonediitj/pydatastructs/blob/master/pydatastructs/miscellaneous_data_structures/queue.py). 
Please start by a draft API design. See, https://github.com/codezonediitj/pydatastructs/wiki/Plan-of-Action-for-the-Projects
P.S. We don't assign issues to contributors. This doesn't mean that you cannot work on this issue. We believe that a PR is important rather than an assignment. Whenever, you will make a PR, that will be linked with this issue and you can keep working on it.

**Comment by anirudh-kac** [comment]
Can I get the format of the draft PR somwhere

**Comment by czgdp1807** [comment]
@anirudh-kac You can explain your draft API in a comment below. See some other issues(BFS, BinomialHeap(closed)) where we have done something similar.

**Comment by anirudh-kac** [comment]
This is the API that I propose
`deque = deque()`
 Inserting elements at front end 
`deque.insert_front(element)`
Inserting elements at rear end
`deque.insert_rear(element)`
Popping from front
`deque.pop_front()`
Popping from rear
`deque.pop_rear()`
Obtaining front element
`deque.front()`
`Obtainig rear element`
`deque.rear()`
Checking for empty deque
`deque.is_empty()`

**Comment by HarsheetKakar** [comment]
Why are we not using collections.deque?

**Comment by czgdp1807** [comment]
We are currently using `collections.deque`.

**Comment by HarsheetKakar** [comment]
> We are currently using `collections.deque`.

I saw Queue and didnt check the imports. oops

**Comment by czgdp1807** [comment]
@anirudh-kac Apologies for the delayed response as I didn't receive the notifications for the same. The API looks good. I would suggest to go along the lines of `Queue`. A new class can be made, `DoublyEndedQueue` which can subclass `Queue` with some extra methods. Or we can also make modifications to the current code of `Queue`(and it's various implementations) and add a simple keyword argument, `doubly_ended` and make it an attribute of the class and do the manipulations to the data structure accordingly. IMO, the second method will require minimal changes in the code base and will get the task done.

**Comment by Jahnavi-Jonnalagadda** [comment]
I would like to work on this issue.

**Comment by czgdp1807** [comment]
@Jahnavi-Jonnalagadda Please srart with the API design. See https://github.com/codezonediitj/pydatastructs/issues/120#issuecomment-597273892 as well. What do you think should we create a new class Or just an extra argument in `Queue.__new__`?

**Comment by SinghHimadri** [comment]
Can I work on this issue? I am new to this project.

**Comment by Arvind-raj06** [comment]
@czgdp1807 Can I take over this issue or if you have a different schedule for me, you can just quote me to work at !

**Comment by czgdp1807** [comment]
TBH, these are simple issues. There are many ideas listed [here](https://github.com/codezonediitj/pydatastructs/wiki/Planned-Features-for-v0.0.1) for which you can discuss the APIs by opening new issues if one for that idea isn't already open. 
It will be better to work on something which demands more thought and discussions before coding.

**Comment by Arvind-raj06** [comment]
> TBH, these are simple issues. There are many ideas listed [here](https://github.com/codezonediitj/pydatastructs/wiki/Planned-Features-for-v0.0.1) for which you can discuss the APIs by opening new issues if one for that idea isn't already open.
> It will be better to work on something which demands more thought and discussions before coding.

Yeah sure I will work on those
