### ISSUE TITLE
popleft and popright should return value

### ISSUE THREAD

**Issue by prshnt19** [codezonediitj/pydatastructs#124]
#### Description of the problem

In liner_data_structures/linked_lists the `pop_left` and `pop_right` functions in return should also return value of the element to be popped.

**Comment by czgdp1807** [comment]
Queue has also a `popleft` method. Does that work correctly?

**Comment by prshnt19** [comment]
Currently, `Queue` is only implemented as `ArrayQueue`. It works correctly. Currently working on `LinkedListQueue`. I will use only the correct implementation.
