### ISSUE TITLE
Parallel Brick Sort

### ISSUE THREAD

**Issue by nehasangeetajha** [codezonediitj/pydatastructs#129]
#### Description of the problem
I would like to propose an odd-even transposition sort or brick sort. Odd-Even Transposition Sort is based on the Bubble Sort technique. It compares two adjacent numbers and switches them if the first number is greater than the second number to get an ascending order list. The opposite case applies to a descending order series.

Please assign me this issue.

**Comment by czgdp1807** [comment]
> In computing, an odd–even sort or odd–even transposition sort is a relatively simple sorting algorithm, developed originally for use on parallel processors with local interconnections. It is a comparison sort related to bubble sort, with which it shares many characteristics. 

[This page](https://en.wikipedia.org/wiki/Odd%E2%80%93even_sort) says that it was originally developed for parallel threads/processors. So, IMO, we should add its parallel implementation with odd indices being sorted on one thread and even indices on another thread. Though before, that a nice API design should be proposed which can be applicable to other parallel sorting algorithms like parallel merge sort. We can develop a uniform API for all parallel sorting algorithms.

**Comment by czgdp1807** [comment]
> Please assign me this issue.

See our issue policy at https://github.com/codezonediitj/pydatastructs/wiki/Issue-Policy

**Comment by Meenakshi2000** [comment]
How to contribute

**Comment by czgdp1807** [comment]
See, https://github.com/codezonediitj/pydatastructs/wiki/Plan-of-Action-for-the-Projects
For this issue specifically we need a parallel version of brick sort. You can think of an idea to make brick sort parallel and we can discuss over it further.

**Comment by MukundVaradarajan** [comment]
Hi, I would like to work on this. Is anyone else already working on it? I have got an idea to go about it.

**Comment by czgdp1807** [comment]
@MukundVaradarajan Please start with an API for brick sort. We need only it's parallel version implemented. IMO, the API for this can along the lines of parallel merge sort already there in the `master`.
See, https://github.com/codezonediitj/pydatastructs/blob/150c6c21ff3157200d75e954406f76d88e271e9d/pydatastructs/linear_data_structures/algorithms.py#L43

**Comment by czgdp1807** [comment]
Parallel implementation of this algorithm is yet to be added.

**Comment by HarsheetKakar** [comment]
we can try one thread for odd and one thread for even part of the array.

**Comment by czgdp1807** [comment]
Some idea is given in https://github.com/codezonediitj/pydatastructs/issues/129#issuecomment-596113494

**Comment by HarsheetKakar** [comment]
> Some idea is given in [#129 (comment)](https://github.com/codezonediitj/pydatastructs/issues/129#issuecomment-596113494)

I can start with a draft PR if its ok?

**Comment by czgdp1807** [comment]
Sure
