### ISSUE TITLE
Add Priority Queue

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#131]
#### References/Other comments
.. [1] https://en.wikipedia.org/wiki/Priority_queue

**Comment by sarthakforwet** [comment]
i wanna take this issue..

**Comment by czgdp1807** [comment]
@sarthakforwet Sure you can. The APIs are defined on the Wikipedia page, so a PR can be made directly.

**Comment by sarthakforwet** [comment]
@czgdp1807  should I have to add a new branch for the pull request to be made because from the current developer branch my previous PR is showing when I click on New PR

**Comment by czgdp1807** [comment]
You can create a new branch by checking out from `master`. Please see https://github.com/codezonediitj/pydatastructs#how-to-contribute and may be https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

**Comment by Disha5harma** [comment]
@czgdp1807 Is this issue still available?

**Comment by czgdp1807** [comment]
@Disha5harma If you can make a better PR than #132 then feel free to do so. The best one will be kept opened and rest will be closed in its favour. Add `PriorityQueue` to `queue.py`.

**Comment by Disha5harma** [comment]
Okay.
Thanks

**Comment by abhishekgupta368** [comment]
I want to work on this issue, can you please assign me?

**Comment by czgdp1807** [comment]
Hi @abhishekgupta368 
Feel free to start work on this issue. Please see our issue policy to get to know how to work on issues.
As you will be adding a new data structure, please go through https://github.com/codezonediitj/pydatastructs/wiki/Plan-of-Action-for-the-Projects for the steps.

**Comment by aravind-karthikeyan** [comment]
Is this still open?

**Comment by czgdp1807** [comment]
@aravind-karthikeyan No one has picked up this issue. Please start by going through the discussion held here in various PRs opened for this issue.

**Comment by meghanagottapu** [comment]
@czgdp1807 can i work on this issue?
