### ISSUE TITLE
Removing some TODOs

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#133]
#### Description of the problem

Currently the `master` has a TODO task of replacing the `collections.deque` with `pydatastructs.Queue`. We have decided not to do this replacement as queue is a very simple data structure and it's efficient implementation is already present in python. In fact, deepcopy.copy will be a bottleneck in doing this replacement so, we shouldn't simply invest our time in this.

**Comment by Riyagoel2** [comment]
I would like to contribute

**Comment by czgdp1807** [comment]
Sure, please proceed with a PR.

**Comment by Riyagoel2** [comment]
Can you please provide any reference

**Comment by czgdp1807** [comment]
For fixing this issue, you just have to look for lines in the codebase having `TODO` and remove those lines.
