### ISSUE TITLE
DynamicOneDimensionalArray could be made faster using ctypes

### ISSUE THREAD

**Issue by prshnt19** [codezonediitj/pydatastructs#136]
`DynamicOneDimensionalArray` could be made faster using `ctypes` array. `ctypes` implementations are 10 to 100 times faster than python and takes less memory than python.

_Originally posted by @prshnt19 in https://github.com/codezonediitj/pydatastructs/pull/118#issuecomment-597312552_

**Comment by HarsheetKakar** [comment]
isnt ctypes like pandas or numpy (internally)?

**Comment by czgdp1807** [comment]
Please see the documentation of ctypes [here](https://docs.python.org/3/library/ctypes.html).

**Comment by robotjellyzone** [comment]
Hi @prshnt19 are still working on this issue ? please give an update !

**Comment by czgdp1807** [comment]
Well, we are going to port the code to C++11 when the design gets stable enough. So, optimising the code for python won't be of much use. Closing this. Thanks for your contributions.
