### ISSUE TITLE
Disjoint-set data structure

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#142]
#### Description of the problem

Disjoint set data structure can have the following APIs,

**Set**
The class `Set` will represent the notion of disjoint sets with respect to the above data structure.
**Attributes**
1. `key` - Any valid key which can be used to uniquely identify this set.
2. `data` - Any valid data or pointers to data can be stored through this.
3. `parent` - The parent of this set. 
4. `size` - The size of the set.
5. `rank` - The rank of the set.

We cannot use static data classes as the `data` attribute will be dynamic.

**DisjointSetTree**
This will represent the notion of disjoint set tree of `DisjointSet`.
**Attribute**
`tree` - A python `dict` for `key` to `DisjointSet` mapping. Hashing here will help us quickly figure out whether a `DisjointSet` is there inside the tree.

**Methods**
1. `make_set(key, data)` - It will make a new set as described in the references.
2. `find(key)` - Finding the root of a particular disjoint set sub tree using path-splitting logic.
3. `union(key1, key2)` - Taking union of sets with given keys by size.

#### References/Other comments
.. [1] https://en.wikipedia.org/wiki/Disjoint-set_data_structure

This is not open for contributions.

**Comment by Dhivyaa-D** [comment]
Can I work on this on this?

**Comment by abhishekgupta368** [comment]
I can do it efficiently, Can you please assign me?

**Comment by robotjellyzone** [comment]
Hi @abhishekgupta368 , are you a participant of GSSOC'20 ?

**Comment by czgdp1807** [comment]
This issue is not open for contributors as written in the description.

**Comment by abhishekgupta368** [comment]
yes, I am participant of GSSOC'20
