### ISSUE TITLE
Add a Skip List Data Structure

### ISSUE THREAD

**Issue by robotjellyzone** [codezonediitj/pydatastructs#149]
#### References/Other comments
[1] https://en.wikipedia.org/wiki/Skip_list

**Comment by asaw4** [comment]
i would like to work on this problem

**Comment by Riyagoel2** [comment]
I would like to work on it as a part of GSSOC

**Comment by czgdp1807** [comment]
@Riyagoel2 @asaw4 You can work on this issue. The first step is to come up with an API design for skip lists. See an example [here](https://github.com/codezonediitj/pydatastructs/wiki/Plan-of-Action-for-the-Projects) for more understanding.

**Comment by kichloo** [comment]
@czgdp1807 Is the issue still open?

**Comment by czgdp1807** [comment]
Hi @kichloo 
@HarsheetKakar is already working on in #171

**Comment by Arvind-raj06** [comment]
@czgdp1807 I will work on this one whilst
