### ISSUE TITLE
Changes in Queue.

### ISSUE THREAD

**Issue by HarsheetKakar** [codezonediitj/pydatastructs#150]
#### Description of the problem
Queue module needs some refactoring.

- Queue methods are generally `enqueue()` and `dequeue()`
- front and rear pointers need to be properties because of their frequent change.
- `type(x) is not self._dtype` can be converted to `_check_type(type(x),self._dtype)` 

This issue was briefly discussed in https://github.com/codezonediitj/pydatastructs/pull/139#issuecomment-598817536 

Further suggestions are welcome.

I will be taking on this issue, since I'm also working on LinkedListStack side by side.

**Comment by HarsheetKakar** [comment]
@czgdp1807 kindly add the points I missed

**Comment by czgdp1807** [comment]
> * Queue methods are generally `enqueue()` and `dequeue()`

Let's not go for it, `push` and `popleft` are in accordance with `collections.deque`. 



> * front and rear pointers need to be properties because of their frequent change.

They both are currently attributes of the `Queue` class. What are the benefits of additionally defining them as properties?

**Comment by HarsheetKakar** [comment]
```
if self.front is None:
            self.front = self.queue.head
        self.rear = self.queue.tail
```
it keeps referring back to self.queue it would be better if we can just move it in a different function/property. Less headache for the programmer and less things to change if we ever have to.

**Comment by HarsheetKakar** [comment]
> > * Queue methods are generally `enqueue()` and `dequeue()`
> 
> Let's not go for it, `push` and `popleft` are in accordance with `collections.deque`.

yeah now to think of it, deque is used as Queue in many places.

**Comment by HarsheetKakar** [comment]
```
if self.is_empty:
            raise ValueError("Queue is empty.")
```
I also dont understand why value error is raised. Something like IndexError would be better (same is used in deque)

**Comment by czgdp1807** [comment]
> ```
> if self.front is None:
>             self.front = self.queue.head
>         self.rear = self.queue.tail
> ```
> 
> it keeps referring back to self.queue it would be better if we can just move it in a different function/property. Less headache for the programmer and less things to change if we ever have to.

Yes, this will help in removing redundant attributes. 



> ```
> if self.is_empty:
>             raise ValueError("Queue is empty.")
> ```
> 
> 
> I also dont understand why value error is raised. Something like IndexError would be better (same is used in deque)

Feel free to make the change. See, if such changes are needed elsewhere in the code base.
Thanks.

**Comment by HarsheetKakar** [comment]
quick question...
`elif type(items) in (list, tuple):`
we are checking against list and tuple only, but I think items can be any `collections.abc.Sequence` type.
Shall I change it to `elif _check_type(items, Sequence)`

**Comment by czgdp1807** [comment]
> Shall I change it to `elif _check_type(items, Sequence)`

I won't recommend.
