### ISSUE TITLE
Multiple tests written under single test name.

### ISSUE THREAD

**Issue by HarsheetKakar** [codezonediitj/pydatastructs#154]
#### Description of the problem
generally one module has one test which has all of the tests implemented in it.

#### Example of the problem
```
def test_Queue():

    q1 = Queue(implementation='array', items=[0])
    q1.append(1)
    q1.append(2)
    q1.append(3)

    q1 = Queue(implementation='linked_list')
    q1.append(1)
    assert raises(TypeError, lambda: Queue(implementation='linked_list', items={0, 1}))
    q1 = Queue(implementation='linked_list', items = [0, 1])
    q1.append(2)
    q1.append(3)
```
This can be changed to
```
test_Queue():
   <tests for Queue abstract class>

test_ArrayQueue():
   <tests for ArrayQueue class>

test_LinkedListQueue():
    <tests for LinkedListQueue class>
```
This will increase readability, and maintaining tests would be easier.

**Comment by HarsheetKakar** [comment]
![image](https://user-images.githubusercontent.com/42893005/76698194-057f2d80-66c6-11ea-9f16-851427e285dd.png)
from here also, if I just want to test ArrayQueue I cant, it will run all the tests for Queue module.

**Comment by czgdp1807** [comment]
> This can be changed to
> 
> ```
> test_Queue():
>    <tests for Queue abstract class>
> 
> test_ArrayQueue():
>    <tests for ArrayQueue class>
> 
> test_LinkedListQueue():
>     <tests for LinkedListQueue class>
> ```
> 
> This will increase readability, and maintaining tests would be easier.

Looks like a nice idea.

**Comment by czgdp1807** [comment]
I think this can be done for stacks as well.

**Comment by HarsheetKakar** [comment]
shall I make a different PR?

**Comment by czgdp1807** [comment]
Yeah, I would recommend to do that. #152 is ready to merge and will be merge soon.

**Comment by HarsheetKakar** [comment]
string in ArrayStack is:
`assert str(s) == '[1, 2, 3]'`

and string in LinkedListStack is:
`assert str(s) == '[3, 2, 1]'`

which of them is better representation of a stack?

**Comment by czgdp1807** [comment]
> string in ArrayStack is:
> `assert str(s) == '[1, 2, 3]'`
> 
> and string in LinkedListStack is:
> `assert str(s) == '[3, 2, 1]'`

As `LinkedListStack` modify the left side of stack and `ArrayStack` modify the right side, both outputs are different. It doesn't matter how they are stored in memory but at least the printing should be consistent. We should follow the representation as used in `ArrayStack`, so the `LinkedListStack` should be reversed before it is printed. Modification in `LinkedListStack.__str__` method is needed.
In addition, `LinkedListStack.top` should be removed. and `LinkedListStack.peek` should return `self.stack.head` rather than `self.stack.head.data`.

**Comment by HarsheetKakar** [comment]
understood
