### ISSUE TITLE
Remove unnecessary aliasing of OneDimensionalArray

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#161]
#### Description of the problem

See, https://github.com/codezonediitj/pydatastructs/blob/b0c3136dfaa6d8551adfa208bcdc76bb3f95dd4f/pydatastructs/linear_data_structures/arrays.py#L130

It has unnecessary aliasing of `OneDimensionalArray`. That line should be removed.

**Comment by HarsheetKakar** [comment]
do u want to alias it in the import or just remove it completely?

**Comment by czgdp1807** [comment]
> do u want to alias it in the import or just remove it completely?

Removing it completely.

**Comment by Aman-Codes** [comment]
I am a GSSOC 2020 participant and I would like to work on it. Please assign it to me.

**Comment by ShebinJoseph** [comment]
Can you please make the problem little more clear,If its a beginner issue,I can work on it

**Comment by czgdp1807** [comment]
The line `ODA = OneDimensionalArray` has to be removed.

**Comment by ShebinJoseph** [comment]
Then,I can do that.This doesn't have any tag.Is problem is considered as contribution in GSSoC20 ?

**Comment by czgdp1807** [comment]
This issue is open for anybody. If you are a GSSoC, 2020 participant then the relevant label will be assigned to your PR and this issue and the scoring will be done accordingly.

**Comment by ShebinJoseph** [comment]
Okay.So this also has score,right ?.Then please assign the issue to me

**Comment by czgdp1807** [comment]
> Then please assign the issue to me

For us a PR matters more than assigning issues. So, whenever you will make a PR and write, `Fixes #161` in it's description it will be automatically linked to this issue. You can work on it. 
See our [issue policy](https://github.com/codezonediitj/pydatastructs/wiki/Issue-Policy) for more details on working on issues.

**Comment by ShebinJoseph** [comment]
okay.I am working on it

**Comment by ShebinJoseph** [comment]
I went to fixes of this issues through stackoverflow,Its mentioned that this error can be ignored.Is that correct ?
