### ISSUE TITLE
LinkedListNode documentation not complete.

### ISSUE THREAD

**Issue by HarsheetKakar** [codezonediitj/pydatastructs#166]
#### Description of the problem
Missing info on links and addrs parameters.

#### Example of the problem
```
class LinkedListNode(Node):
    """
    Represents node in linked lists.

    Parameters
    ==========

    data
        Any valid data to be stored in the node.
    """
    def __new__(cls, data=None, links=['next'], addrs=[None]):
```

**Comment by czgdp1807** [comment]
Feel free to add the necessary information.

**Comment by HarsheetKakar** [comment]
Honestly speaking I have no idea what links or addrs is doing.

**Comment by czgdp1807** [comment]
`links` is a list containing the names of attributes which should be used as links to other nodes. For example if you want to create a node for doubly linked lists then you can pass, `links = ['next', 'prev']`. `addrs` is contains the address of nodes to be assigned to each of the attributes in `links`. 
This is done for using only a single node class for various kind linked lists with differences in the number of links only.

**Comment by HarsheetKakar** [comment]
why do we have 2 lists for that then? shouldn't it be in a dict maybe?

**Comment by urbashi123** [comment]
I want to work on documetation.Can i work on it?
