### ISSUE TITLE
Add note of caution in `minimum_spanning_tree(_parallel)`

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#185]
#### Description of the problem

The concept of MST is valid only for connected and undirected graphs. If the graph is disconnected and undirected, the result will not be an MST but a forest consisting of many MSTs. However, for directed graphs, result can be anything.
To fix this issue just apply 
[pds_diff.txt](https://github.com/codezonediitj/pydatastructs/files/4363179/pds_diff.txt)
 by using `git apply [path to pdf_diff.txt]`.

#### References/Other comments
.. [1] https://en.wikipedia.org/wiki/Edmonds%27_algorithm

**Comment by sar99** [comment]
Hello sir,
Can I submit a PR for this issue?

**Comment by czgdp1807** [comment]
Hi @sar99 
Sure. Are you participating through `gssoc20`?

**Comment by sar99** [comment]
Yes sir, I am a participant in gssoc20.
