### ISSUE TITLE
Cocktail Sort 

### ISSUE THREAD

**Issue by TechnoPhasePRO** [codezonediitj/pydatastructs#198]
#### Description of the problem

The code added sorts the array of numbers with minimum complexity as compared to bubble sort.

#### References/Other comments
https://en.wikipedia.org/wiki/Cocktail_shaker_sort

**Comment by TechnoPhasePRO** [comment]
@czgdp1807 please assign me this issue.

**Comment by TechnoPhasePRO** [comment]
following is the API design for the cocktail sort :->

`def cocktailsort()`: The cocktail sort function is similar to bubble sort . It traverse thorough both 
                       directions while sorting the array. The complexity in comparison is less.
         `list`: It contains the list of elements to be sorted.
         `first`:  first indicates the first index of the array
         `last`: last indicates the last index element of the array
         `k`:  variable that counts the length of the array
         `t`:  variable is used to denote if array is sorted after the sorting process. It is initialized 1 to 
             check if array is sorted after every iteration.
        `temp`: It is used as third variable to exchange the values.
        `while t != 0`: After each iteration, the value of t is reset which is evaluated in while condition. If value of t is 1, the control skips the iteration process.
        `for i in range(first, last, 1)`: this for loop will do the forward sort. the greatest element after each 
                                                 pass will be at the last index. This for loop will do the forward sort
                                                 the greatest element after each pass will be at the last index.
        `if t == 0`: t is initialized to 1 to check if the loop was sorted or not in the forward sort.
                      if value of t was not changed the control will jump off the loop. Else the control will 
                      move to the backward sort.
        `for i in range(last, first - 1, -1)`: the next loop will do the backward sort in the array. Value of first 
                                                        variable is increased every time as smallest element is found after 
                                                        backward sort.
        `return (list)`: It returns the sorted array.

**Comment by TechnoPhasePRO** [comment]
@czgdp1807 Please review my API design for cocktail sort.

**Comment by czgdp1807** [comment]
@TechnoPhasePRO 
It looks like you have provided the complete implementation. See the suggestions I have made below.
Cocktail sort is good as a sequential algorithm. However, if thought carefully we can parallelise it by using two threads, one thread moving from left to right and another moving from right to left simultaneously. The thing to be taken care of is to avoid a scenario where the equation, `i = (n - 1)/2` has integer solutions for `i`. As in that case both the threads will clash and only one thread should be allowed process i and then the other one. Concept of locks can be used for this particular `i` to avoid inconsistency. 

I would suggest the following APIs,

1. `cocktail_shaker_sort(array, **kwargs)` - `kwargs` can be used to pass, `start` and `end`.
2. `cocktail_shaker_sort_parallel(array, num_threads, **kwargs)` - Similar case for `kwargs`.

**Comment by TechnoPhasePRO** [comment]
@czgdp1807 i want to add the PR for this , that's why i proposed API first but @bandaabhigna already added PR without any API ,  i think this is wrong ????

**Comment by aditimaurya** [comment]
Hello, can you please assign this issue to me?

**Comment by czgdp1807** [comment]
Please read https://github.com/codezonediitj/pydatastructs/wiki/Issue-Policy
