### ISSUE TITLE
Array should be able to convert all sequence type to OneDimensionalArray.

### ISSUE THREAD

**Issue by HarsheetKakar** [codezonediitj/pydatastructs#206]
#### Description of the problem

as list can convert any iterable to list, OneDimensionalArray should also be able to convert range, OrderedSet, string etc to OneDimensionalArray

**Comment by HarsheetKakar** [comment]
and also Array abstract class should be extended from sequence class

**Comment by czgdp1807** [comment]
What are the benefits of doing so?

**Comment by HarsheetKakar** [comment]
1: OneDimensionalArray can already convert string to array if we let it.
2: list can convert any sequence to list, so if we can make array to do the same transition from list to array would become smoother for the user
3: OneDimensionalArray can't take its own object. It is not important but if developer isnt careful and if he/she tries to convert an array again it would give a traceback.
4: Making ODA a sequence will make it more like list, strings etc.

These are some of the things it will improve as well as it is a good practice to make such classes as extensions of sequence because I feel like users will expect them to be like that.

**Comment by czgdp1807** [comment]
> list can convert any sequence to list, so if we can make array to do the same transition from list to array would become smoother for the user

`list` can store elements of different types but array don't allow that. The reason being the addressing part. Though this is a theoritical limit, but IMHO, this should be respected and at many places in the package, lists are allowed as input to various algorithms and data structures.

> OneDimensionalArray can't take its own object. It is not important but if developer isnt careful and if he/she tries to convert an array again it would give a traceback.

Please give an example.

> Making ODA a sequence will make it more like list, strings etc.

ODA is very different from `list`, `str`(both of these are also different).

>  deepcopy does not work on ODA currently

`deepcopy` doesn't work with many user defined classes for reasons undiscovered. We can make our own deepcopy framework but that won't be really very useful and worth of resources and time.

**Comment by HarsheetKakar** [comment]
> `list` can store elements of different types but array don't allow that. The reason being the addressing part. Though this is a theoritical limit, but IMHO, this should be respected and at many places in the package, lists are allowed as input to various algorithms and data structures.

we can do the different type check after allowing the sequence.

> Please give an example.
```
>>> from pydatastructs import OneDimensionalArray
>>> a = OneDimensionalArray(int, [1,2,3])
>>> b = OneDimensionalArray(int, a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\projects\pydatastructs\pydatastructs\linear_data_structures\arrays.py", line 107, in __new__
    raise TypeError("Expected type of size is int and "
TypeError: Expected type of size is int and expected type of data is list/tuple.
```
> ODA is very different from list, str(both of these are also different).

Thats not the main point, the main point is that we can convert string to a list and vice versa which makes it easier to deal with.

>deepcopy doesn't work with many user defined classes for reasons undiscovered. We can make our own deepcopy framework but that won't be really very useful and worth of resources and time.

I think if we correct the above example this deepcopy will work

**Comment by czgdp1807** [comment]
> we can do the different type check after allowing the sequence.

Please explain more.

I tried deepcopy and observed the following, 

```python
>>> from pydatastructs import OneDimensionalArray as ODA
>>> from copy import deepcopy
>>> a = ODA(int, [1, 2, 3])
<class 'int'> ([1, 2, 3],) {}
>>> deepcopy(a)
<class 'NoneType'> () {}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 274, in _reconstruct
    y = func(*args)
  File "/usr/lib/python3.6/copyreg.py", line 88, in __newobj__
    return cls.__new__(cls, *args)
  File "/home/czgdp1807ssd/codezonediitj/pydatastructs/pydatastructs/linear_data_structures/arrays.py", line 71, in __new__
    raise ValueError("1D array cannot be created due to incorrect"
ValueError: 1D array cannot be created due to incorrect information.
>>> 
```
I am not sure that if ODA takes it's own object in the constructor then the deepcopy will work. Some other classes give a similar behaviour. The use case which you are suggesting requires `copy` constructor which isn't available in python other than `copy` module.



> Thats not the main point, the main point is that we can convert string to a list and vice versa which makes it easier to deal with.

Well, we can do as many changes to `ODA`, it will be of very little use as `list`, `string` are supported in many places across the package. `DODA` is much more useful where frequent deletions and appends(such as trees) are to be made as it allows nice trade-off between memory, and time. Otherwise arrays aren't of use unless they provide optimisations which cannot happen if we are using lists internally.

**Comment by HarsheetKakar** [comment]
ok I guess I was trying to over engineer it. I still think the ability to take ODA object in the constructor will help in long run, and some changes in DODA which can help in dealing with None values (eg. iterator which will only return till the _last_pos_filled)
