### ISSUE TITLE
implement `__reversed__()` in Array

### ISSUE THREAD

**Issue by HarsheetKakar** [codezonediitj/pydatastructs#209]
#### Description of the problem

currently reversed() returns a python list if OneDimensionalArray object is given, it should return ODA object.

**Comment by czgdp1807** [comment]
Minor changes are needed, you can do it.

**Comment by HarsheetKakar** [comment]
lets resolve #206 and I will bundle all the changes in one PR

**Comment by czgdp1807** [comment]
#206 is a very different issue. Please make separate PR for this one.

**Comment by HarsheetKakar** [comment]
small correction in the title above, it returns a reversed generator object.

**Comment by HarsheetKakar** [comment]
I think i got confused with sorted and reversed, I am applying the changes in DODA, and not in ODA because it will work as it does with or without method overriding. Sorry for confusion
