### ISSUE TITLE
Add Queue

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#22]
#### Description of the problem

Currently we use `Queue` from `collections` module. We want that this should be implemented in `pydatastructs` itself, however, without breaking the current code, i.e., the API should be similar to the one of `collections` module.

API:

1. An empty queue should be constructed by using `Queue()`.

2. New elements should be added to the end by using `.append(elem)`.

3. The elements should be removed from the front using `.popleft()`.

4. The number of elements in the queue should be returned by `len` i.e, `__len__` method should be over-rided in the `Queue` class.

#### References/Other comments
See the code of `OneDimensionalSegmentTree` in `pydatastructs.tree.space_partitioning.trees` and `BinaryTreeTraversal.breadth_first_search` to know more about the API requirements.

**Comment by abhstract** [comment]
Can you please assign this issue to me??also  I am new to python so I might take some time.

**Comment by czgdp1807** [comment]
You can start working on this issue. Take your time for creating a PR for this.

**Comment by abhstract** [comment]
thanks

**Comment by abhstract** [comment]
For data type what are the parameters that we have to consider?
