### ISSUE TITLE
Add Trie data structure.

### ISSUE THREAD

**Issue by HarsheetKakar** [codezonediitj/pydatastructs#229]
#### References/Other comments
[Reference](https://www.geeksforgeeks.org/trie-insert-and-search/)

**Comment by czgdp1807** [comment]
Please propose an API for the Trie data structure.

**Comment by HarsheetKakar** [comment]
TrieNode:
The class `TrieNode` will extend from Node base class to represent a node in `Trie`
Attributes:
- `children`- array of None initially for number of symbols possible.
- `is_end`- Boolean to represent leaf position.

Trie:
The class `Trie` to represent data structure Trie.
Attributes:
- `root`- start `Node`.
- `symbols`- symbols expected to be searched in `Trie`
- `size`- total nodes in `Trie`

Methods:
- `insert(string)`: insert a string in Trie
- `search(string)`: takes string and returns True if full match else returns list of partial matches
- `delete(string)`: delete a string from Trie
- `_index(symbol: Char)`: takes in symbol and gives it index position in `Node.children`

**Comment by czgdp1807** [comment]
> * `_index(symbol: Char)`: takes in symbol and gives it index position in `Node.children`

Why do we need this?

**Comment by czgdp1807** [comment]
> * `children`- array of None initially for number of symbols possible

Can we go for python dict with `TrieNode` as key?

**Comment by czgdp1807** [comment]
> * `size`- total nodes in `Trie`

Why we need this too?

**Comment by HarsheetKakar** [comment]
> > * `children`- array of None initially for number of symbols possible
> 
> Can we go for python dict with `TrieNode` as key?

sure, would be better

**Comment by HarsheetKakar** [comment]
> > * `_index(symbol: Char)`: takes in symbol and gives it index position in `Node.children`
> 
> Why do we need this?

not if we use dict

**Comment by HarsheetKakar** [comment]
> > * `size`- total nodes in `Trie`
> 
> Why we need this too?

not really needed.

**Comment by robotjellyzone** [comment]
Hi @HarsheetKakar are still working on this ? Any update ?

**Comment by rohitrox444** [comment]
I want to Work on this issue
