### ISSUE TITLE
_left_rotate and _right_rotate in SelfBalancingBinaryTree

### ISSUE THREAD

**Issue by Aimaanhasan** [codezonediitj/pydatastructs#234]
#### Description of the problem

The existing methods of `_left_rotate` and `_right_rotate` in the `SelfBalancingBinaryTree` are not working properly as it assumes j as the left child of parent in `_right_rotate` and right child of parent in `_left_rotate`, which causes conflict in some nodes.

#### Example of the problem

```
>>> tree = SelfBalancingBinaryTree()
		 
>>> tree.insert(5,5)
		 
>>> tree.insert(5.5,5.5)
		 
>>> tree.insert(4.5,4.5)
		 
>>> tree.insert(4.6,4.6)
		 
>>> tree.insert(4.4, 4.4)
		 
>>> tree.insert(4.55, 4.55)
		 
>>> tree.insert(4.65, 4.65)
		 
>>> print(tree)
		 
[(2, 5, 5, 1), (None, 5.5, 5.5, None), (4, 4.5, 4.5, 3), (5, 4.6, 4.6, 6), (None, 4.4, 4.4, None), (None, 4.55, 4.55, None), (None, 4.65, 4.65, None)]
>>> tree._right_rotate(3, 5)
		 
>>> print(tree)
		 
[(2, 5, 5, 1), (None, 5.5, 5.5, None), (5, 4.5, 4.5, 3), (None, 4.6, 4.6, 6), (None, 4.4, 4.4, None), (None, 4.55, 4.55, 3), (None, 4.65, 4.65, None)]
>>> tree.tree[3].parent
		 
5
>>> tree.tree[2].right
		 
3
```

In this example node at index 3 has parent 5, while node at index 2 has 3 as one of its children. Since there cannot be two parents at the same time, this is a conflict.

**Comment by Aimaanhasan** [comment]
See PR #235

**Comment by czgdp1807** [comment]
The rotation methods of `SelfBalancingTree` are only used in it's child classes. So, the above example may not be a compelling reason to make a fix. Can you please try the same example out with `AVLTree`? Compare the outputs by visualisations generated in https://www.cs.usfca.edu/~galles/visualization/AVLtree.html by the same series of operation.

**Comment by czgdp1807** [comment]
> See PR #235 for FIX

The fix for the bug(if it exists) should be made in a separate PR for maintaining git history in a better way.

**Comment by czgdp1807** [comment]
Confirmed. This is a bug. Thanks for pointing out.

**Comment by Aimaanhasan** [comment]
I am making a 

> > See PR #235 for FIX
> 
> The fix for the bug(if it exists) should be made in a separate PR for maintaining git history in a better way.

Creating a new PR for FIX
