### ISSUE TITLE
Add some links to data structure visualisation websites

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#236]
#### Description of the problem

Some data structure visualisation links can be added to README under [testing guide](https://github.com/codezonediitj/pydatastructs#testing) so that's easier for the developer to test their code efficiently.

**Comment by arathyrose** [comment]
Hi, this website: [https://visualgo.net/en](https://visualgo.net/en) has pretty good visualisations in data structures and algorithms through animation. May I add it in the readme?

**Comment by czgdp1807** [comment]
Sure. Add https://www.cs.usfca.edu/~galles/visualization/ as well.
