### ISSUE TITLE
Add Fenwick Tree

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#24]
#### Description of the problem

Fenwick trees are quite popular data structure and should be added to the package.

#### References/Other comments
https://en.wikipedia.org/wiki/Fenwick_tree

**Comment by RashakDude** [comment]
@czgdp1807 Can you assign me this issue :)

**Comment by czgdp1807** [comment]
You can start working on this issue by proposing the API. 
Please read the complete plan of action at https://github.com/codezonediitj/pydatastructs/wiki/Plan-of-Action-for-the-Projects
Thanks.

**Comment by aravind-karthikeyan** [comment]
Is this still open? Can I work on this issue?

**Comment by czgdp1807** [comment]
@aravind-karthikeyan Yes. Please see my above comment and start accordingly.

**Comment by iamrajiv** [comment]
@czgdp1807 I would like to work on this. Is it available?
