### ISSUE TITLE
Correct order of parameters in doc strings

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#251]
#### Description of the problem

As of now, the order of `Parameters` in docstrings of classes/functions doesn't align with the order required in their prototype. For example, `TreeNode(key, data=None)` then the order of parameters in doc strings should be,
```
Parameters
=========

key
...

data
...
```

and NOT,

```
Parameters
=========

data
...

key
...
```
All doc strings should be checked for this consistency for closing this issue.

**Comment by Amitsharma45** [comment]
can you explain this issue in detial

**Comment by Rukmini-Meda** [comment]
I would like to work on this issue. Please assign this to me as part of GSSoC'20.

**Comment by robotjellyzone** [comment]
Hi @Rukmini-Meda yes, you can work on this issue go ahead!
