### ISSUE TITLE
Proposal: We should use metaclass to enforce derived classes to implement certain functions.

### ISSUE THREAD

**Issue by HarsheetKakar** [codezonediitj/pydatastructs#252]
#### Description of the problem

Currently if we want someone to implement a particular function we put it in base class and raise a NotImplementedError if someone skips it in the derived class. The problem comes when it isnt called. Programmer can simply use `push` instead of `append` and it wouldn't give an error simply because the method not being used by the user. It will also pass all tests, and the user would be able to see it in the methods of the class but they wont be able to use them. It can be a problem when a multilevel inheritance takes place since the moderator wont necessarily be able to see which function is not being implemented.

If we implement metaclass it will raise error if the derived class does not have a set method in place. This will help removing the bugs in long run and help the moderator find the exact methods not implemented without reading a lot of code.

**Comment by czgdp1807** [comment]
Which classes are causing such problems as of now?

**Comment by HarsheetKakar** [comment]
As of now it isnt, but there is a potential of problems which for example if I inherit from `Queue` in some other file for maybe creating some other queue like datastructure, and instead of `append` I implement the function `push`. If the user is using vs code or maybe `inspect` module to get the names of method it will give both `push` and `append` but when the user uses append it gives `NotImplementedError`.

Worse example is if someone implements `pop_left` instead of `popleft` maybe you miss it since there are no errors in testing and it gets into the master branch.

**Comment by czgdp1807** [comment]
As of now, there is a practice of creating an interface class and then defining various implementation classes after inheriting the interface class. So, if abstract methods like, `popleft` is there in the base class and `pop_left` is defined in the child class and someone uses `pop_left` in the tests then simply there will be no errors but `popleft` will show the `NotImplementedError`. What are the benefits of `metaclasses` over using the framework of interface classes and implementation classes?

**Comment by HarsheetKakar** [comment]
>  uses pop_left in the tests then simply there will be no errors but popleft will show the NotImplementedError.

exactly there will not be errors in case of `pop_left` and both `popleft` and `pop_left` will make their way to the master branch if the code reviewer messes it up. Right now we have one code reviewer, but if in the future if there are several of them and one does not remember to look up in the base class if all the methods that need to be implemented are being implemented in derived class. This can be removed by using meta classes as if `popleft` is not made in derived then it will raise an error right away helping the developer and the reviewer in finding the method name and in which class it is not being implemented.

**Comment by czgdp1807** [comment]
Well, meta classes aren't there in C++ right now and when we will port the code to C++, Metaclasses may make things difficult. Instead of complicating things, can we just extend the code quality tests to confirm that a subset of methods for every class is implemented. Like, we can have a list of classes which are in global namespace(public API is what that matters). There should be a static method(in interface class) which will return the methods which must be implemented and the tests will make a call to all of them(for each of the class) and raise error when some of them aren't implemented. That would be easy to add and easy to maintain as compared to Metaclass.
