### ISSUE TITLE
Enforcing implementations of certain methods in classes

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#254]
#### Description of the problem

As highlighted in https://github.com/codezonediitj/pydatastructs/issues/252 there are good chances that API can become inconsistent if certain methods aren't named properly and such mistakes are missed in the review process. So, a solution should be proposed to solve this problem satisfying the following conditions,

1. A set of certain methods should be implemented(i.e., shouldn't raise `NotImplementedError`) in every class. If some methods from the given set of methods isn't implemented then that should be detected in CI.
2. The solutions should be simple enough such that it can be easily ported to C++11.

One of the approaches is described at https://github.com/codezonediitj/pydatastructs/issues/252#issuecomment-610999089

#### References/Other comments
Please discuss your approach first rather than jumping to code directly.

**Comment by HarsheetKakar** [comment]
One way is to use something like __init_subclass__ if it works or plain old collections.abc should work too
