### ISSUE TITLE
PCA

### ISSUE THREAD

**Issue by AparnaJuhi** [codezonediitj/pydatastructs#263]
Dimensionality Reduction Algo of dataset

**Comment by AparnaJuhi** [comment]
Principal component analysis (PCA) is a technique used to emphasize variation and bring out strong patterns in a dataset. It's often used to make data easy to explore and visualize.

**Comment by AparnaJuhi** [comment]
I wanna work on this issue @czgdp1807

**Comment by czgdp1807** [comment]
Thanks for the contributions. 
There are many optimised implementations of PCA already available. You can see one of them [here](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html). In addition, PCA is more useful in the domains of ML. Closing this issue as it is not in scope of the project.
