### ISSUE TITLE
Reference for tests

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#264]
#### Reference for tests
- URL: https://opendatastructures.org/ods-python.pdf

_Originally posted by @Aimaanhasan in https://github.com/codezonediitj/pydatastructs/pull/235#issuecomment-619012765_

The above URL can be added to README under `Testing` section.

**Comment by Souvikns** [comment]
can you assign it to me

**Comment by czgdp1807** [comment]
You can work on it.

**Comment by Souvikns** [comment]
I have created a pull request 

https://github.com/codezonediitj/pydatastructs/pull/266
