### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by anirudh-kac** [codezonediitj/pydatastructs#273]
#### Description of the problem
I suggest adding quicksort algorithm in linear data structures
i.e linear_data_structures.algorithms.quick_sort()

There are some sorting algorithms already there, with same nlogn complexity, but since most inbuilt sorting algorithms are implemented using quicksort, we should also add quick sort

**Comment by czgdp1807** [comment]
Thanks. IMHO, parallel implementation of iterative quick sort should be added. API discussion isn't needed as quick sort should follow the APIs of existing sorting algorithms.

**Comment by anirudh-kac** [comment]
Sure, I'll Start Working

**Comment by Moddy2024** [comment]
i am from gssoc 2020 and i would like to work on this

**Comment by czgdp1807** [comment]
@Moddy2024 Sure you can. But make sure you have read the README file, and the discussion in this issue and #274

**Comment by Moddy2024** [comment]
i have created a pull request for  the quick_sort algorithm please review it

**Comment by AishwaryaVarma** [comment]
i would like to work on this- im from gssoc'20

**Comment by Moddy2024** [comment]
i am from GSSOC'20  and i have again created a pull request with a better code please look into it @czgdp1807 @aayush-05 @manaswinidas @robotjellyzone

**Comment by robotjellyzone** [comment]
but where is your PR @Moddy2024 ?

**Comment by Moddy2024** [comment]
> but where is your PR @Moddy2024 ? can you paste the reference for your PR here ?

yeah sure

**Comment by seshasaisuhashdesu** [comment]
Is this issue still open? Can i look into it?

**Comment by RhuthuHegde** [comment]
Can I work on this issue if this is open?

**Comment by czgdp1807** [comment]
Sure.

**Comment by RhuthuHegde** [comment]
Have you assigned it to me?

**Comment by czgdp1807** [comment]
Please read https://github.com/codezonediitj/pydatastructs/wiki/Issue-Policy

**Comment by RhuthuHegde** [comment]
Can you give me an insight on how, to begin with, as I am completely new to open source?

**Comment by RhuthuHegde** [comment]
Can you give me an insight on how to begin with this problem, as I am new to open source.

**Comment by czgdp1807** [comment]
I'd suggest to first read the [README file](https://github.com/codezonediitj/pydatastructs/blob/master/README.md) before starting to code.
For this issue specifically, you just need to add a new function to [this file](https://github.com/codezonediitj/pydatastructs/blob/master/pydatastructs/linear_data_structures/algorithms.py) and add a test for quick sort in [this file](https://github.com/codezonediitj/pydatastructs/blob/master/pydatastructs/linear_data_structures/tests/test_algorithms.py). Just see the pattern of code and add your changes.

**Comment by Utkarsh-Agarwal-585** [comment]
Sir, please assigned me this issue. I want to contribute

**Comment by czgdp1807** [comment]
Sure. You can a submit PR for this issue. Getting assigned isn't a compulsory requirement in this project as I have repeated many times in previous comments.
