### ISSUE TITLE
Add `__slots__` in classes

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#29]
#### Description of the problem

Refer, http://book.pythontips.com/en/latest/__slots__magic.html

#### References/Other comments
This is issue is open for anyone to fix.

**Comment by udhayacommits** [comment]
hello @czgdp1807,
I am trying this one out.
I am a newbie so please bear with me and let me know if something is off.

**Comment by czgdp1807** [comment]
Hi, 

This issue is very easy to fix. You just have to check which class is not having, `__slots__` list and add the same to those classes. Note that the list should contain every attribute of the class. Take a look at `pydatastructs.linear_data_structures.arrays.DynamicOneDimensionalArray`, I have added the `__slots__` list there.
