### ISSUE TITLE
Replace tests of binary tree with in-order and pre-order

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#294]
#### Description of the problem

As of now, the correctness of operations on a binary tree is determined by verifying the `str(tree)` with the expected string. This makes it quite difficult to check the tests. Instead of using, `str(tree)`, in-order and pre-order should be checked since, using both these traversals a binary tree can be uniquely constructed.

#### Example of the problem

See the tests of RedBlackTree.

#### References/Other comments
[1] https://github.com/codezonediitj/pydatastructs/pull/293

**Comment by Vanshikagarg17** [comment]
I am from GSSoC 2020, I would like to work upon this.

**Comment by prshnt19** [comment]
@Vanshikagarg17 Sure. Just have a look at https://github.com/codezonediitj/pydatastructs#how-to-contribute if not already done so.

**Comment by ravisrc** [comment]
Can I take up on this, or is it closed (since there was a pull request) ?

**Comment by czgdp1807** [comment]
Sure.

**Comment by ravisrc** [comment]
I have opened this Pull request #304 which solves this issue.
