### ISSUE TITLE
.editorconfig file

### ISSUE THREAD

**Issue by HarsheetKakar** [codezonediitj/pydatastructs#296]
#### Description of the problem
We should have a .editorconfig file instead of tests for endline and trailing whitespaces.

#### Example of the problem
Currently we have to explicitly review each PR for extra endline, trailing whitespace etc.

#### References/Other comments
We can simply insert these rules and dev's editor will enforce them for us.
```
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

```

**Comment by czgdp1807** [comment]
Is this file compatible with any editor/IDE?

**Comment by czgdp1807** [comment]
> Currently we have to explicitly review each PR for extra endline, trailing whitespace etc.

Quality tests fail when there are trailing newlines and trailing whitespaces.

**Comment by HarsheetKakar** [comment]
> Is this file compatible with any editor/IDE?

works with many out of the box (eg vscode, pycharm) but in some editors like atom a plugin is needed to be installed

**Comment by HarsheetKakar** [comment]
> > Currently we have to explicitly review each PR for extra endline, trailing whitespace etc.
> 
> Quality tests fail when there are trailing newlines and trailing whitespaces.

I have seen that in many PRs it gets overlooked and newcomers dont understand why thier code is failing. .editorconfig just makes it that much easier and removes the need of most of the quality tests

**Comment by czgdp1807** [comment]
Okay then, we can add this file without removing anything from the package.

**Comment by HarsheetKakar** [comment]
cool, working on it then
