### ISSUE TITLE
Longest common subsequence

### ISSUE THREAD

**Issue by khushibalyan220101** [codezonediitj/pydatastructs#308]
Description of the problem
LCS Problem Statement: Given two sequences, find the length of longest subsequence present in both of them. A subsequence is a sequence that appears in the same relative order, but not necessarily contiguous.
Example of the problem
For example, “abc”, “abg”, “bdf”, “aeg”, ‘”acefg”, .. etc are subsequences of “abcdefg”.

**Comment by khushibalyan220101** [comment]
@czgdp1807 sir I wanna contribute with this problem by creating a specific file for dynamic programming problems so that other important questions can be collected in a particular file.

**Comment by czgdp1807** [comment]
This can go to a new file, `miscellaneous_algorithms` under `pydatastructs`. Please go through the README for better understanding the workflow before submitting a PR.

**Comment by khushibalyan220101** [comment]
Sure sir, I will go through the README.

**Comment by LazarusCoder** [comment]
i have added a algorithm in algorithms.py
Do i need to modify the API too for that ??
or just need to add function name in JSON which is already there in algorithms.py??

**Comment by LazarusCoder** [comment]
LCS with BackTracking added in linerstruture->algorithms.py
Test cases Added too
"Fixes #310 "
