### ISSUE TITLE
README.md file enhancement.

### ISSUE THREAD

**Issue by anirudhsai20** [codezonediitj/pydatastructs#333]
#### Description of the problem

The README.md file does not have the list of all the open source programs in which this is a part of. It also does not include the list of research papers in which this is cited. It also does not have a display of all its contributors. It also features a lot of grammatical errors in the description.

#### References/Other comments
The README.md file can be further enhanced by adding a list of Open source programs, its contributors, resesrch papers and correcting the grammatical errors.

**Comment by anirudhsai20** [comment]
Hi! Please allow me to work on this issue under SWOC.

**Comment by czgdp1807** [comment]
> The README.md file does not have the list of all the open source programs in which this is a part of.

It is not necessary to add a list of open source programs where we participated.

> It also does not include the list of research papers in which this is cited.

I am not aware of any where this project is cited. It would be better to do focus on citations once we go for our first release.

>  It also does not have a display of all its contributors. 

Check the `AUTHORS` file. Contributors can add their names to this file if they want to be counted as author of this project.

>  It also features a lot of grammatical errors in the description.

Please feel free to correct them in  your PR.

> Hi! Please allow me to work on this issue under SWOC.

Sure.
