### ISSUE TITLE
Syntax Error in graphs/graph.py

### ISSUE THREAD

**Issue by malay5** [codezonediitj/pydatastructs#339]
#### Description of the problem

Syntax error present in graph.py, which throws Syntax Warning. When the package is called and used to run a simple "Hello World" problem.

#### Example of the problem

![DELETE](https://user-images.githubusercontent.com/64472685/110591162-b8ca1780-819e-11eb-83c7-5775e368415b.JPG)

**Comment by czgdp1807** [comment]
@malay5 Are you participating via GSSoC or any other open source program?

**Comment by malay5** [comment]
> @malay5 Are you participating via GSSoC or any other open source program?

Yeah! participating via GSSoC
