### ISSUE TITLE
Replace `Node` by `TreeNode` and `GraphNode`

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#34]
#### Description of the problem

Currently we have  a generic `Node` class which basically has methods and data members for trees. However, when we will add graphs, the above `Node` class will not be compatible.
It would be better to use specific classes for, trees i.e., `TreeNode`(rename `Node` -> `TreeNode`) and a new `GraphNode`.
This issue aims at discussing the API for the latter.

**Comment by raajtilaksarma** [comment]
Can I take this issue? The current class `Node` in `https://github.com/codezonediitj/pydatastructs/blob/master/pydatastructs/utils/misc_util.py` is to be changed to `TreeNode` right?

**Comment by czgdp1807** [comment]
Yes. The other thing to be done is to discuss and finalise the API of `GraphNode` i.e., what data members and methods it should have. But we will do that later once `Node` is replaced by `TreeNode` across the modules.

**Comment by raajtilaksarma** [comment]
Okay. On it. Can you add the KWOC label to this issue?

**Comment by czgdp1807** [comment]
Let's discuss the API for `GraphNode` now. If you have anything suggest then please comment. Refer https://github.com/codezonediitj/pydatastructs/pull/17 and https://github.com/codezonediitj/pydatastructs/issues/13

**Comment by raajtilaksarma** [comment]
So next we need to create a class `GraphNode` right?

**Comment by czgdp1807** [comment]
Yes but before that we need to discuss its API.

**Comment by czgdp1807** [comment]
@raajtilaksarma Are you working on it?

**Comment by raajtilaksarma** [comment]
I will start tomorrow. Can you brief me on the API? By api do you mean
properties of the GraphNode like its methods and variables?

**Comment by czgdp1807** [comment]
> By api do you mean
properties of the GraphNode like its methods and variables?

Yes, especially user facing methods and variables. Refer the issue and PRs, links to which I have shared in other comment. 
Once you suggest your ideas, we will improve on it.

**Comment by raajtilaksarma** [comment]
Cool will do so. I am checking out the wikipedia link of graphnode u shared.

**Comment by raajtilaksarma** [comment]
Should we have 2 classes for directed and undirected graph node?

**Comment by czgdp1807** [comment]
I don't think because both undirected and directed graph can be represented in terms of each other. For example if we use adjacency list or adjacency matrix then both can represent generic graphs.

**Comment by raajtilaksarma** [comment]
Okay
