### ISSUE TITLE
(GSSOC21) algorithm : Multiplying Large integer number

### ISSUE THREAD

**Issue by banshita209** [codezonediitj/pydatastructs#341]
#### Description of the problem

I am GSSOC 21 participant.
I like to implement Multiplying two large integer algorithms in this project.

#### References/Other comments

@czgdp1807 kindly assign it to be me so that I can contribute to my open source journey of GSSOC

**Comment by Smit-create** [comment]
I don't think that in python we require such algorithms as python as no limits on int range. I mean it can perform arithmetic operations on very long numbers too:
See:
```py
>>> x = 1002020203002040300202030404020200304042478294
>>> y = 1930403985858372665254894003004
>>> x*y
1934303793785754310930707070567642313829483156437578226400718685614440795176
```
Moreover, contributions are always welcomed. You can refer to the present issues list and see if you could raise a PR for that.

**Comment by Smit-create** [comment]
@czgdp1807  This can be closed.

**Comment by czgdp1807** [comment]
Big integer algorithms are already there in python. So we do not need to worry about such things for now. When we will move to C++, we will see if we want to use Boost or write our own algorithms for this.
