### ISSUE TITLE
2d Matrix Manipulation

### ISSUE THREAD

**Issue by anuragmukherjee2001** [codezonediitj/pydatastructs#355]
#### Description of the problem

This data structure is a package of functions which deals with different types of manipulations with a 2d array. This python program will contain functions like adding a 2d matrix, subtracting a 2d matrix, multiplication, and many more. 

2d matrix manipulation is very necessary in out real world problems, and python is definitely a good programming language to understand this data structure in an easy way.

#### References/Other comments

I am a GSSOC'21 participant and want to contribute for this project. I will write clear code with sufficient comments, so that everyone can understand the code and the concept.

So, I request you to kindly assign this issue to me.

**Comment by Smit-create** [comment]
What algorithm you will use for 2D matrix multiplication?

**Comment by czgdp1807** [comment]
`numpy` already specializes in these things. Closing.
