### ISSUE TITLE
Implement sparse matrix using linked list

### ISSUE THREAD

**Issue by aaadddiii** [codezonediitj/pydatastructs#357]
#### Description of the problem
A matrix is a two-dimensional data object made of m rows and n columns, therefore having total m x n values. If most of the elements of the matrix have 0 value, then it is called a sparse matrix

#### References/Other comments
https://en.wikipedia.org/wiki/Sparse_matrix

**Comment by yasht01** [comment]
Hey! Can I work on this issue?
