### ISSUE TITLE
ADD ANAGRAMS CODE

### ISSUE THREAD

**Issue by srisatya1197** [codezonediitj/pydatastructs#360]
I want to add anagram code in String directory . Please assign me this issue as participant of GSSOC'21.
EXAMPLE 1:
Input - Triangle
        Integral
Output- Triangle and Integral are anagrams.
EXAMPLE 2: 
Input - Just
           Oust
Output - Just and Oust are not anagrams.

**Comment by Smit-create** [comment]
Please see https://github.com/codezonediitj/pydatastructs/issues/343 for effective ideas
