### ISSUE TITLE
Find median [heaps]

### ISSUE THREAD

**Issue by hridhi** [codezonediitj/pydatastructs#362]
#### Description of the problem
Given an input stream of N integers. The task is to insert these numbers into a new stream and find the median of the stream formed by each insertion of X to the new stream.

#### Example of the problem
N = 4
X[] = 5,15,1,3
Output:
5
10
5
4
#### References/Other comments
https://practice.geeksforgeeks.org/problems/find-median-in-a-stream-1587115620/1

part of GSSoC'21

**Comment by Smit-create** [comment]
We should always focus on some generalized problem. This can be easily done by `ordered_set` (as we have in cpp) which has tree based implementation. It would be nice if you could add something like `ordered_set`.
