### ISSUE TITLE
Tower of Hanoi

### ISSUE THREAD

**Issue by Srishti013** [codezonediitj/pydatastructs#386]
The tower of Hanoi is a famous puzzle where we have three rods and N disks. The objective of the puzzle is to move the entire stack to another rod. You are given the number of discs N. Initially, these discs are in the rod 1. You need to print all the steps of discs movement so that all the discs reach the 3rd rod. Also, you need to find the total moves.

It is an important recursion problem and I would like to provide its code in python.

**Comment by Smit-create** [comment]
Hi @Srishti013,
This is a very specific problem. We try to add generalized DS, or algorithm. Please look at : https://github.com/codezonediitj/pydatastructs/issues/343 for more ideas.
