### ISSUE TITLE
Trie Data Structure

### ISSUE THREAD

**Issue by AmarKamalapuri** [codezonediitj/pydatastructs#387]
I want to add Trie Data Structure in python in Data Structure Directory.

I am a GSSOC participant. Can u please assign this issue to me?
@Harsheet-saxena @pristineVedansh @manaswinidas @seshasaisuhashdesu @din1881

**Comment by Smit-create** [comment]
Already present: https://github.com/codezonediitj/pydatastructs/blob/master/pydatastructs/strings/trie.py
