### ISSUE TITLE
Add `multiset` to `pydatastructs.miscellaneous_data_structures`

### ISSUE THREAD

**Issue by Muskan0** [codezonediitj/pydatastructs#390]
#### Description of the problem

https://github.com/codezonediitj/pydatastructs/issues/390#issuecomment-986180523

> We do have SelfBalancingBinaryTree we just need to put pop method (which is basically show top and delete). Apply pop enough time and we have tree sort. My point being that we don't need to reinvent anything.

**Comment by Komal-99** [comment]
I would like to work kn this issue kindly assign it to  me .I am gssoc'21 participant

**Comment by Smit-create** [comment]
Can we create a `multiset` using this? I would prefer having the implementation which is available in CPP where Insert, deletion, and count works in O(logN)?

**Comment by Muskan0** [comment]
@Smit-create Can I do it in Python?

**Comment by Amulya310** [comment]
Please assign this issue to me under Gssoc'21.

**Comment by HarsheetKakar** [comment]
> Can we create a `multiset` using this? I would prefer having the implementation which is available in CPP where Insert, deletion, and count works in O(logN)?

We do have `SelfBalancingBinaryTree` we just need to put pop method (which is basically show top and delete). Apply pop enough time and we have tree sort. My point being that we don't need to reinvent anything.

**Comment by skullVoid** [comment]
Shall I work on this?

**Comment by czgdp1807** [comment]
We already have plenty of sorting algorithms. Having one more makes sense? Though I like the idea of `multiset`, it is a data structure worth adding.

**Comment by Smriti123Shukla** [comment]
Kindly assign this issue to me under Gssoc'22

**Comment by czgdp1807** [comment]
@Smriti123Shukla You can go ahead with adding `multiset`. We don't assign issues. Please read, https://github.com/codezonediitj/pydatastructs/wiki/Issue-Policy
