### ISSUE TITLE
Wave Sort

### ISSUE THREAD

**Issue by U-c0de** [codezonediitj/pydatastructs#396]
#### Description of the problem
If there are multiple sorted orders in wave form, return the one which is lexicographically smallest. The array may contain duplicates.

#### Example of the problem
Input:  arr[] = {2, 4, 6, 8, 10, 20}
 Output: arr[] = {4, 2, 8, 6, 20, 10} OR
                 any other array that is in wave form

@czgdp1807 Assign me this issue

**Comment by Smit-create** [comment]
This is not useful. Look at #343
