### ISSUE TITLE
Add difference b/w ODA and DODA

### ISSUE THREAD

**Issue by pratikgl** [codezonediitj/pydatastructs#406]
#### Description of the problem
The difference b/w OneDImensionalArray (ODA) and DynamicOneDimensionalArray (DODA) is not very clear. It isn't easy to use and differentiate b/w these arrays, especially for newcomers

I think simply adding a line stating the difference between ODA and DODA here will be enough. https://github.com/codezonediitj/pydatastructs/blob/0edbadaf3b2b27c9fbdfd1e5e8c430fd8388f126/pydatastructs/linear_data_structures/arrays.py#L268

**Comment by czgdp1807** [comment]
Thanks. Please feel free to make a PR on this.

**Comment by pratikgl** [comment]
Great. Working on it.
