### ISSUE TITLE
Add salient features in the main page of website

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#421]
#### Description of the problem

We should provide compelling reasons in the documentation so that people are tempted to use our project. 

#### References/Other comments

I will work on this.

**Comment by nidz27** [comment]
I would like to work on this issue. Please assign it to me and tell me more about what should I do.

**Comment by czgdp1807** [comment]
I added it in #428. Probably #428 was merged in a branch other than `master`, so this issue wasn't closed automatically. Doing it now. Sorry for the confusion.

**Comment by czgdp1807** [comment]
@nidz27 Feel free to work on other issues. Just leave a comment on the issue you want to work on.
