### ISSUE TITLE
Add pydatastructs.test function to run tests

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#436]
#### Description of the problem

The above function would make it easier for the user to verify the installation of PyDataStructs APIs.

**Comment by ShubhamNagure** [comment]
I'd like to work on it

**Comment by czgdp1807** [comment]
Sure. Go ahead.

**Comment by ShubhamNagure** [comment]
Can you please assign this to me?

**Comment by czgdp1807** [comment]
Hey @ShubhamNagure. We don't assign issues. You can read our issue policy, https://github.com/codezonediitj/pydatastructs/wiki/Issue-Policy
