### ISSUE TITLE
Boyer Moore Algorithm

### ISSUE THREAD

**Issue by Bhavesh0027** [codezonediitj/pydatastructs#463]
Implement a string matching algorithm - Boyer Moore

Example of the problem
Input: 
      txt[] = "THIS IS A TEST TEXT"
      pat[] = "TEST"
Output: 
     Pattern found at index 10

Reference #400

**Comment by GnanambhalSvRam** [comment]
Hello! Can you add me (Gnanambhal S) to this issue for GSSOC'22?

**Comment by czgdp1807** [comment]
@GnanambhalSvRam Please feel free to start working on this. We don't assign issues. Please read, https://github.com/codezonediitj/pydatastructs/wiki/Issue-Policy

**Comment by Abekaesh** [comment]
Hello I would like to work on this issue for GSoC 2023. Can I work on this?

**Comment by czgdp1807** [comment]
Sure go ahead. You can add your implementation in https://github.com/codezonediitj/pydatastructs/blob/master/pydatastructs/strings/algorithms.py for Boyer Moore algorithm.
