### ISSUE TITLE
Multithreaded merge_sort

### ISSUE THREAD

**Issue by dejokz** [codezonediitj/pydatastructs#476]
Description of the problem
implementation of multi-threaded merge sort that takes the list as input, and returns the sorted list by using multithreaded merge sort. This is part of SWoC

Example of the problem
merge_sort_parallel([5,4,3,2,1], ascending = True))
1, 2, 3, 4, 5
merge_sort_parallel([2, 4, 6, 8], ascending = False)
8, 6, 4, 2

References/Other comments
CLRS: chapter 27: Multithreaded algorithms
Not sure under which file hierarchy should this python file come under? Perhaps a new directory can be created to facilitate multithreaded algorithms.

**Comment by czgdp1807** [comment]
Thanks but it's already there - 

https://github.com/codezonediitj/pydatastructs/blob/97cb9fdd177f11b763c3f72ead11b4ba525ce4ed/pydatastructs/linear_data_structures/algorithms.py#L64
