### ISSUE TITLE
Network flow: Edmon Karp algorithmn

### ISSUE THREAD

**Issue by dejokz** [codezonediitj/pydatastructs#478]
#### Description of the problem
Network flow problem as described [here](https://github.com/codezonediitj/pydatastructs/issues/477), but solving it with Edmon Karp's algorithmn

#### References/Other comments
[Video](https://youtu.be/RppuJYwlcI8)

**Comment by czgdp1807** [comment]
Sure go ahead.

**Comment by Smit-create** [comment]
Fixed in #530
