### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by youknowqyh** [codezonediitj/pydatastructs#479]
#### Description of the problem

When I run `import pydatastructs`, there will be an `ImportError`.

#### Example of the problem

![image](https://user-images.githubusercontent.com/59754711/148655340-7f9d3505-974d-4592-b548-b350df366173.png)

**Comment by czgdp1807** [comment]
Please check the updated instructions on README.

**Comment by youknowqyh** [comment]
> Please check the updated instructions on README.

Solved! Thx :-)
