### ISSUE TITLE
Add Linked Lists

### ISSUE THREAD

**Issue by rohansingh9001** [codezonediitj/pydatastructs#49]
#### Description of the problem
Currently the package does not have Queues or Linked Lists. 
While working with issue #22-Add Queue  
It was discovered that to add a Queue which is efficient enough to perform popleft() action in O(1) time we need linked lists to implement Queues just like the collections.deque implementaion of a Queue.

Since the original goal of issue #22 was to reduce dependencies on other libraries, LInked List must be added to pydatastructs to ensure an efficient implementation of Queues.

#### Example of the problem

>>> sample_queue = Queue()
>>> for i in range(N) # N be a large number
...        sample_queue.append('#')
...
>>> sample_queue.popleft() # Takes O(N) time
#

#### References/Other comments

See the original issue -
https://github.com/codezonediitj/pydatastructs/issues/22

Read about the efficiency issue here -
https://www.geeksforgeeks.org/deque-in-python/
https://stackoverflow.com/questions/55578874/dequeue-complexity-on-using-python-list-as-a-queue

**Comment by rohansingh9001** [comment]
I have already written the code for Double LInked LIsts I am Currently Adding Single Linked Lists
and Documentation within the code.
After this I can start working on Queue which should not take much time

**Comment by czgdp1807** [comment]
Please discuss the API first before moving on to a PR. Share your code here in the comments.

**Comment by rohansingh9001** [comment]
API for Double Linked List:

1) A Doubly linked list should be initialised with `DoubleLinkedList()`

2) Elements can be pushed at the start of the list using `.push(data)`

3) Elements can be appended at the end using `.append(data)`

4) Elements can be popped from the list at a certain index by `.pop(index)` 

5) `__getitem__` and `__setitem__` support using python syntax, 
eg - 
 `list[1]`
` list[5] =4` 

6) Print the Linked List in List form using `print()` function 
eg - 
if elements in linked list named `sample_list` are 1-2-3-4
`>>>print(sample_list)`
`[1,2,3,4]`

7) Return length of the Linked List using `len()` function. 

8) `.popright()` and `.popleft()` pops items from the right and the left respectively.

9) `.insertAt(index, data)` inserts a new Node at the index.

10) `.insertBefore(Node, data)` and `.insertAfter(Node, data)` inserts a new Node before and after the input Node respectively.

API names can be changes easily in order to keep them parallel with norms please suggest any change in the names of the functions.

The temporary code has been attached to this comment. Documentaion is incomplete. Some examples with expected output has been provided at the end.
/home/rohan/Desktop/github/pydatastructs/pydatastructs/linear_data_structures/linked_list.py

**Comment by rohansingh9001** [comment]
I am facing difficulties ataching my code so I have copied the code in the comment itself.

`
#from pydatastructs.utils.misc_util import _check_type, NoneType
_check_type = lambda a, t: isinstance(a, t)
NoneType = type(None)
'''
functions from misc_util.py copied temporarily
untill the script is complete
'''

__author__ = 'rohansingh9001'

__all__ = [
    'DoublyLinkedList'
]

# A linked list node 
class Node: 

    '''
    Node class for Linked List and Doubly Linked List [ Intended for internal use and not to be imported]

    -----------------------------------------Parameters----------------------------------------
    
    For Doubly Linked List >> Default constructor(__init__):

        data: type
            A valid object type.
            Should be convertible to string using str() method to use print() method on instance

    For Single Linked List >> Alternative constructor(singleLink):
        data: type
            A valid object type
            Should be convertible to string using str() method to use print() method on instance
    
    ------------------------------------------Note--------------------------------------------

    classmethod singleLink has been used for Node class for Single linked list due to non existence of a 
    previous link between the nodes.
    '''

    __slots__ = ['data', 'next', 'prev']
    # Constructor to create a new node 
    def __init__(self, data): 
        self.data = data 
        self.next = NoneType
        self.prev = NoneType
    #Alternative constructor for Single Linked List
    @classmethod
    def singleLink(cls, data):
        cls.data = data
        cls.next = NoneType
        return cls
    
    def __str__(self):
        return str(self.data)
  
# Class to create a Doubly Linked List 
class DoublyLinkedList: 
    

    '''
    A Doubly Linked List (abb. DLL)
    -------------------------------------------Parameters-------------------------------------------
    
    None

    ---------------------------------------------Methods--------------------------------------------

    1) push: 
        takes parameters - data
            data: type 
                A valid object type
                Should be convertible to string using str() method to use print() method on instance

        action - Pushes a new node at the start i.e. left of the DLL.

    2) append: 
        takes parameters - data
            data: type
                A valid object type
                Should be convertible to string using str() method to use print() method on instance

        action - Appends a new node at the end i.e. the right of the DLL
    
    3) insertAfter:
        takes parameters - prevNode, data
            prevNode: Node type 
                An object of Node class 
            data: type
                A valid object type
                Should be convertible to string using str() method to use print() method in instance

        action - inserts a new node after the prevNode


    -------------------------------------------References-------------------------------------------
    
    => https://www.geeksforgeeks.org/doubly-linked-list/

    '''

    #Constructor to create a DLL
    def __init__(self):
        
        self.head = NoneType
        self.tail = NoneType
        self.length = 0

    #Push method 
    def push(self,data):
        
        self.length += 1
        newNode = Node(data)
        if self.head is not NoneType:
            self.head.prev = newNode
            newNode.next = self.head
        self.head = newNode

        if newNode.next == NoneType:
            self.tail = newNode
        if newNode.prev == NoneType:
            self.head = newNode

    def append(self, data):
        
        self.length += 1
        newNode = Node(data)
        if self.tail is not NoneType:
            self.tail.next = newNode
            newNode.prev = self.tail
        self.tail = newNode

        if newNode.next == NoneType:
            self.tail = newNode
        if newNode.prev == NoneType:
            self.head = newNode
    
    def insertAfter(self, prevNode, data):
        
        self.length += 1
        newNode = Node(data)
        newNode.next = prevNode.next
        prevNode.next = newNode
        newNode.prev = prevNode
        
        if newNode.next == NoneType:
            self.tail = newNode
        if newNode.prev == NoneType:
            self.head = newNode

    def insertBefore(self, nextNode, data):
        
        self.length += 1
        newNode = Node(data)
        newNode.prev = nextNode.prev
        nextNode.prev = newNode
        newNode.next = nextNode
        
        if newNode.next == NoneType:
            self.tail = newNode
        if newNode.prev == NoneType:
            self.head = newNode

    def insertAt(self, index, data):
        
        if index > self.length or index < 0 or not (_check_type(index, int)):
            raise ValueError('Index input out of range/Index is expected to be an Integer.')
        
        else:

            if index == 0:
                self.push(data)
            elif index == self.length:
                self.append(data)

            else:
                
                self.length += 1
                newNode = Node(data)
                counter = 0
                currentNode = self.head
                
                while counter != index:
                    currentNode = currentNode.next
                    counter += 1

                currentNode.prev.next = newNode
                newNode.prev = currentNode.prev
                currentNode.prev = newNode
                newNode.next = currentNode
                    
                if newNode.next == NoneType:
                    self.tail = newNode
                if newNode.prev == NoneType:
                    self.head = newNode
    
    def popleft(self):

        self.length -= 1
        oldHead = self.head
        oldHead.next.prev = NoneType
        self.head = oldHead.next
        
        return oldHead.data 

    def popright(self):

        self.length -= 1
        oldTail = self.tail
        oldTail.prev.next = NoneType
        self.tail = oldTail.prev

        return oldTail.data

    def pop(self, index=0):
        
        if index > self.length or index < 0 or not (_check_type(index, int)):
            raise ValueError('Index input out of range/Index is expected to be an Integer.')
        
        else:
            
            if index == 0:
                self.popleft()
            elif index == self.length:
                self.popright()
            
            else:
                
                self.length -= 1
                counter = 0
                currentNode = self.head
                
                while counter != index:
                    currentNode = currentNode.next
                    counter += 1
                
                currentNode.prev.next = currentNode.next
                currentNode.next.prev = currentNode.prev

                return currentNode.data

    def __getitem__(self, index):
        
        if index > self.length or index < 0 or not (_check_type(index, int)):
            raise ValueError('Index input out of range/Index is expected to be an Integer.')
        
        else:
            
            counter = 0
            currentNode = self.head
                
            while counter != index:
                currentNode = currentNode.next
                counter += 1

            return currentNode.data

    def __setitem__(self, index, data):

        if index > self.length or index < 0 or not (_check_type(index, int)):
            raise ValueError('Index input out of range/Index is expected to be an Integer.')

        else:
            
            counter = 0
            currentNode = self.head
                
            while counter != index:
                currentNode = currentNode.next
                counter += 1

            currentNode.data = data

    
    def __str__(self):
        elements = []
        currentNode = self.head

        while currentNode is not NoneType:
            elements.append(currentNode.data)
            currentNode = currentNode.next

        return str(elements)

    def __len__(self):
        return self.length


if __name__ == '__main__':
    '''
    Temporary Tests to test the code
    Will not affect the code when imported.
    Test can be run by running the python script.
    Expected Output --
    -------------------------------------Linked List Info-----------------------------------
    Head : <class 'NoneType'>
    Tail : <class 'NoneType'>
    []
    Length : 0
    -------------------------------------Linked List Info-----------------------------------
    Head : 5
    Tail : 5
    [5]
    Length : 1
    -------------------------------------Linked List Info-----------------------------------
    Head : 6
    Tail : 5
    [6, 5]
    Length : 2
    -------------------------------------Linked List Info-----------------------------------
    Head : 6
    Tail : 10
    [6, 5, 10]
    Length : 3
    -------------------------------------Linked List Info-----------------------------------
    Head : 6
    Tail : 10
    [6, 5, 7, 10]
    Length : 4
    -------------------------------------Linked List Info-----------------------------------
    Head : 3
    Tail : 10
    [3, 6, 5, 7, 10]
    Length : 5
    -------------------------------------Linked List Info-----------------------------------
    Head : 3
    Tail : 10
    [3, 6, 5, 4, 7, 10]
    Length : 6
    -------------------------------------Linked List Info-----------------------------------
    Head : 6
    Tail : 10
    [6, 5, 4, 7, 10]
    Length : 5
    -------------------------------------Linked List Info-----------------------------------
    Head : 6
    Tail : 7
    [6, 5, 4, 7]
    Length : 4
    -------------------------------------Linked List Info-----------------------------------
    Head : 6
    Tail : 7
    [6, 5, 7]
    Length : 3
    6
    5
    7
    currentNode : <class 'NoneType'> 6 0
    currentNode : 6 0 7
    currentNode : 0 7 <class 'NoneType'>
    '''

    def printinfo(LL):
        print('-------------------------------------Linked List Info-----------------------------------')
        print('Head :', LL.head)
        print('Tail :', LL.tail)
        print(LL)
        print('Length :', len(LL))

    LL = DoublyLinkedList()
    printinfo(LL)

    LL.push(5)
    printinfo(LL)

    LL.push(6)
    printinfo(LL)

    LL.append(10)
    printinfo(LL)

    LL.insertAt(2, 7)
    printinfo(LL)

    LL.insertAt(0, 3)
    printinfo(LL)

    LL.insertAt(3, 4)
    printinfo(LL)

    LL.popleft()
    printinfo(LL)

    LL.popright()
    printinfo(LL)\

    LL.pop(2)
    printinfo(LL)

    print(LL[0])
    print(LL[1])
    print(LL[2])

    LL[1] = 0

    for i in range(len(LL)):
        print('currentNode :', currentNode.prev, currentNode, currentNode.next)
        currentNode = currentNode.next
`

**Comment by czgdp1807** [comment]
> 2\. Elements can be pushed at the start of the list using `.push(data)`
 
`appendleft` would be a better name. 

> 4\. Elements can be popped from the list at a certain index by `.pop(index)`

What would be the amortized time complexity of this operation?

**Comment by czgdp1807** [comment]
I will comment on the code you shared just now a bit later.

**Comment by rohansingh9001** [comment]
It would have to traverse through the string so the `.pop(index)`
will take O(n) in worst case scenarios.

I cannot find any way to improve upon this without making extra arrays and increasing the memory consumed by the List. If you are aware of any methods please share any resources so I can add it.

The operations at the ends take O(1) time though.

Also should I change the `.append()` to `.appendright` in view of symetry?

I was facing difficulty uploading the .py file so I have uploaded the txt file with the code 
[linked_list.txt](https://github.com/codezonediitj/pydatastructs/files/3972941/linked_list.txt)

**Comment by czgdp1807** [comment]
The code is fine but follow the coding style of the code in current master, especially the documentation. Please read the guidelines in the read me file. The code should go in a new file under, `linear_data_structures` folder with the name, `linked_lists`.
Please use cite reliable references in the code, like wikipedia. Make separate PRs for adding each type(singly linked lists, doubly linked lists, etc.) for better management.

**Comment by rohansingh9001** [comment]
Sorry for the sudden absence, due to my current location in Delhi, internet services were down due to some orders and I could not inform you before leaving for travelling. I have learned a bit about code coverage in the meantime and I will resume work on the single linked lists.

**Comment by rohansingh9001** [comment]
I have read the feedback. I will make sure to follow them in any future PRs. :)

**Comment by prshnt19** [comment]
Is it resolved?

**Comment by czgdp1807** [comment]
Only doubly linked lists are added as of writing this comment.

**Comment by prshnt19** [comment]
Should there be a single `CircularLinkedList` or two of them- implemented using `SinglyLinkedList` 
 and `DoublyLinkedList`?

The API for `CircularLinkedList` should contain basic functions (`insert`, `delete`, `displayList`)
or all the functions of `DoublyLinkedList`?

**Comment by czgdp1807** [comment]
What about having, `SinglyCircularLinkedList` and `DoublyCircularLinkedList`?

**Comment by prshnt19** [comment]
`SinglyCircularLinkedList` and `DoublyCircularLinkedList` are fine. They can be inherited from `SinglyLinkedList` and `DoublyLinkedList` respectively.

**Comment by prshnt19** [comment]
I thought LinkedList implementation of `Queue` and `Stack` are under this issue.
API for `Queue`:
`Enqueue`: Adds an item to the queue.
`Dequeue`: Removes an item from the queue
`Front`: Get the front item from the queue.
`Rear` (optional): Get the last item from the queue.
`isEmpty`: Returns true if the Queue is empty, else false.

API for `Stack`:
`push`: Adds an item in the stack.
`pop`: Removes an item from the stack.
`top`: Returns the top element of the stack.
`isEmpty`: Returns true if the stack is empty, else false.

Should they be inherited from already defined `SinglyLinkedList` or defined as a new class?

**Comment by czgdp1807** [comment]
The design of base class `Queue` can be followed for the class `LinkedListQueue` and similarly for `LinkedListStack`, the design of base class `Stack` can be followed.

https://github.com/codezonediitj/pydatastructs/blob/19cabb2f50395ddd15a2783820171bf157e81893/pydatastructs/miscellaneous_data_structures/queue.py#L49-L67

https://github.com/codezonediitj/pydatastructs/blob/19cabb2f50395ddd15a2783820171bf157e81893/pydatastructs/miscellaneous_data_structures/stack.py#L49-L71 



> Should they be inherited from already defined `SinglyLinkedList` or defined as a new class?

No, we don't need to inherit `SinglyLinkedList`. See `ArrayStack` and `ArrayQueue` class and a similar kind of implementation is needed for the linked list implementations.

**Comment by prshnt19** [comment]
The `Stack` and `Queue` class have to be defined in `linear_data_structures` or in `miscellaneous_data_structures`.
