### ISSUE TITLE
docs: Add Issue Templates

### ISSUE THREAD

**Issue by maityamit** [codezonediitj/pydatastructs#497]
#### Description of the problem
Changes
Adding Issue templates
Template path  ``` .github/ISSUE_TEMPLATE ``` 

#### Example of the problem

**Template Types**

![156198784-b2e8d551-3df4-4aff-a7c7-051a88c344c0](https://user-images.githubusercontent.com/74618071/156574710-6e75dbde-7ee9-4cb7-9297-c516d5092eb8.png)
![156169861-53b91128-a1aa-4751-805e-affb8a4924a3](https://user-images.githubusercontent.com/74618071/156574718-869a8c87-a672-4d4a-a32e-61e60fb0c6bc.png)

Contribution towards GSsoc`22, Thank you

**Comment by czgdp1807** [comment]
Already there https://github.com/codezonediitj/pydatastructs/blob/master/ISSUE_TEMPLATE.md
