### ISSUE TITLE
Confirm a question 

### ISSUE THREAD

**Issue by mohanadtalat91** [codezonediitj/pydatastructs#501]
Hello Sir, 
Should I complete or finish any function or method that contains the following line at the end of each function ?? 
I see every function that contains the following line is empty and need to implement, so I need just a confirmation of my thoughts. Am I right or not ? 

Thanks in advance Sir. 

https://github.com/codezonediitj/pydatastructs/blob/8c91a6a89dd5806dcc6aaff8efa0fcc38ebd676b/pydatastructs/linear_data_structures/linked_lists.py#L68

**Comment by czgdp1807** [comment]
Abstract methods are not implemented anyways. The code in `master` branch is correct.
