### ISSUE TITLE
Tests using `raises` are not being asserted

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#52]
#### Description of the problem

I was observing the test files and found that tests which use `raises` are not being asserted which was due to absence of `return` statement in, 
https://github.com/codezonediitj/pydatastructs/blob/8da8f36b1243a9acd0105c422baccc05831da936/pydatastructs/utils/raises_util.py#L3-L16

However with merging of https://github.com/codezonediitj/pydatastructs/pull/51 `raises` will return `True` on successful execution, hence all the tests of the following format,
```python
raises(...)
``` 
are to be replace with the format below,
```python
assert raises(...)
```

**Comment by TarunTomar122** [comment]
I can do this! Please assign it to me..

**Comment by czgdp1807** [comment]
Thanks for the interest. You can start working on it.
Please let us know if you are participating through any open source program (KWoC, amDeC).
P.S. We only assign issues to those who have write access to the repository. In other cases, any number of people can work on any issue.
