### ISSUE TITLE
Next greater element using stack

### ISSUE THREAD

**Issue by Volcano-Dragon** [codezonediitj/pydatastructs#526]
#### Description of the problem
Hey, I want to add a famous algorithm used to find the next greater element using stack. Please assign me this issue in Python. Thank you!

#### Example of the problem
The first greater element in the array to the right of an element x is known as the Next Greater Element for that element.
When there is no greater element for an element, the next greater element is treated as -1

#### References/Other comments
I would like to work on this project as a part of GSSoC 23. Please assign this issue to me.

**Comment by Jasmineck** [comment]
Hello @Volcano-Dragon  I am familiar with this topic and believe I can do the task efficiently. Can you please assign this project to me with tag GSSOC'23 .
