### ISSUE TITLE
`obj = object.__new__(cls)`

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#57]
#### Description of the problem

Currently any class object is created by,
```python
obj = object.__new__(cls)
```
For better readability, each such line should be replaced by the abstract superclass of that class.
Something like,
```python
obj = <name_of_abstract_super_class>.__new__(cls)
```
For example, in `arrays.py`,  `OneDimensionalArray` is created by, 
https://github.com/codezonediitj/pydatastructs/blob/9c32d4068ace96da9b953ea678b1c2fd852d141c/pydatastructs/linear_data_structures/arrays.py#L73
However, the above should be replaced by,
```python
obj = Array.__new__(cls)
```

**Comment by alpeshjamgade** [comment]
hey,  i would like to work on this.

**Comment by czgdp1807** [comment]
Thanks for the interest. You can start working on it.

**Comment by TarunTomar122** [comment]
For all the classes that are inheriting from superclass Object this line should remain the same, Isn't it?

**Comment by czgdp1807** [comment]
@TarunTomar122 Yes, if class S is the class at the topmost level in the inheritance hierarchy then any child C below S in the hierarchy should create its objects something like,
```python
def __new__(cls, ...):
    obj = S.__new__(cls)
    ...
    return obj
```
