### ISSUE TITLE
Add algorithms for LCA in BinaryTree.

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#62]
#### Description of the problem

Refer, https://github.com/codezonediitj/pydatastructs/pull/27

**Comment by nethish** [comment]
Hi! Is this open. Can I work on this?

**Comment by czgdp1807** [comment]
Hi, You can start your work on this. I would suggest to cherry pick the commit from #27

**Comment by iamrajiv** [comment]
@czgdp1807 I would like to work on this. Is it available?

**Comment by iamrajiv** [comment]
@czgdp1807 I would like to work on this. Is it available?

**Comment by czgdp1807** [comment]
@nethish is working on this issue. If he gives up then feel free to take over this issue.
