### ISSUE TITLE
Use DynamicOneDimensionalArray in ArrayStack

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#67]
#### Description of the problem

Currently we use fixed size arrays in `ArrayStack` which is nothing but wastage of memory. To reduce that problem, `DynamicOneDimensionalArray`should be used inside the methods of `ArrayStack`.

The way of using is left to the one who will fix the issue.

**Comment by Saptashrungi** [comment]
I am willing to work on this issue. Is an Arraystack a static one dimensional array?

**Comment by czgdp1807** [comment]
Yes, currently we are using, `OneDimensionalArray` inside `ArrayStack` which needs `maxsize` to be given for creating the object. 
May be, we need to make the changes with affecting the API. See the examples of `DynamicOneDimensionalArray` to understand its usage.

**Comment by Saptashrungi** [comment]
I went through one of the example for dynamic array. It used ctype module and doubled the size of array when it's capacity was full.

**Comment by czgdp1807** [comment]
The `DynamicOneDimensionalArray` doesn't use any external module named `ctype`.
Yes, the size of the array is doubled everytime it becomes full to keep the amortized cost of insertion, O(1). Similarly in the case of deletion we half the size of the array when only 1/4 of the total capacity is used to keep the amortized cost of deletion, O(1).
Read more about it at the following links,
[1] http://www.cs.nthu.edu.tw/~wkhon/algo09/lectures/lecture16.pdf
[2] https://www.cs.cornell.edu/courses/cs3110/2013sp/lectures/lec21-amortized/lec21.html

**Comment by czgdp1807** [comment]
The working of `DynamicOneDimensionalArray` shouldn't be our concern while using it in `ArrayStack`. We just need to figure out how to use it's public methods i.e., `append` and `delete` in `pop` and `push`.

**Comment by Saptashrungi** [comment]
I read about amortized cost. We need to use already existing methods of Arraystack in DynamicOneDimensionalArray right?

**Comment by czgdp1807** [comment]
> We need to use already existing methods of Arraystack in DynamicOneDimensionalArray right?

You are thinking the opposite of what is required. We need to use the methods of `DynamicOneDimensionalArray` in `ArrayStack`.
For example in the following line, replace `OneDimensionalArray` with `DynamicOneDimensionalArray`
https://github.com/codezonediitj/pydatastructs/blob/a8e2a96d77f4ff2380163f382b7bac06b315d073/pydatastructs/miscellaneous_data_structures/stack.py#L93
Similarly in the following `push`,
https://github.com/codezonediitj/pydatastructs/blob/a8e2a96d77f4ff2380163f382b7bac06b315d073/pydatastructs/miscellaneous_data_structures/stack.py#L104-L108
can be re-written as,
```python
def push(self, x):
    self.items.append(self.dtype(x))
```
In a similar manner, you have to see what changes are required in other methods of `ArrayStack`.

**Comment by Saptashrungi** [comment]
There is no need of top because we are appending right?

**Comment by czgdp1807** [comment]
> There is no need of top because we are appending right?

Yes, the purpose of `top` will be fulfilled by `self.items._last_pos_filled`.



> The append function is not user defined I assume.

The `append` function is the one defined in `DynamicOneDimensionalArray`. We are just using it in `ArrayStack` as I showed in https://github.com/codezonediitj/pydatastructs/issues/67#issuecomment-569264634

**Comment by Saptashrungi** [comment]
For pop I suggest the following like the example given by you;

Current pop function:
 
` def pop(self):
        if self.top == 0:
            raise ValueError("Stack is already empty.")
        self.top -= 1
        r = self.items[self.top]
        self.items[self.top] = None
        return r`

Modified pop function:
 def pop(self):
        self.items.delete(-1)

#assuming the delete function displays the item before deleting.

**Comment by czgdp1807** [comment]
May be we can use deepcopy to copy the top most element before deleting it. Something like,
```python
def pop(self):
    top_element = copy.deepcopy(self.items[self._last_pos_filled])
    self.items.delete(self._last_pos_filled)
    return top_element
```
What do you say?

**Comment by Saptashrungi** [comment]
Why not a simple copy? Is the item having a subclass?

**Comment by czgdp1807** [comment]
We don't know what will be there in the stack. It can be anything. May be an object(in which case `deepcopy` is necessary, otherwise, a reference will be created which will be modified on deletion and at the wrong value will be returned). IMHO, we have to be generalise. 
I am not sure will work in all cases, but that shouldn't be our problem as it is inbuilt, so python should take care of it. 

> Why not a simple copy?

Can you try this out on your system? Does `pop` return correct values?

**Comment by Saptashrungi** [comment]
Okay, then using deepcopy would be better. You want me to try and check pop with deepcopy right?

**Comment by czgdp1807** [comment]
Well, if `deepcopy` is the only option we have, then you can go for a PR, if there's nothing more to discuss.

**Comment by Saptashrungi** [comment]
Yes because a simple copy won't clone the values of child objects.

**Comment by Saptashrungi** [comment]
May be we should try this also:

''' def pop(self):
    top_element = self.items[self._last_pos_filled]
    self.items.delete(self._last_pos_filled)
    return top_element'''

**Comment by czgdp1807** [comment]
I think it would create shallow copy which will be changed on deletion. `top_element` will be a reference to `self.items[self._last_pos_filled]` which will be made `None` by `self.items.delete(self._last_pos_filled)` and hence user will always receive `None` as the return value, which we don't want.
However, you can still try that out, if that works for user defined class objects then we can go for it.
