### ISSUE TITLE
Add `.vs` files to `.gitignore`

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#71]
#### Description of the problem

`.vs` files are not ignore as can be seen in https://github.com/codezonediitj/pydatastructs/pull/66
They should be added to `.vs` files as they are automatically generated by system, probably only on Windows.

**Comment by NeelavaChatterjee** [comment]
Can you assign this issue to me?

**Comment by czgdp1807** [comment]
You can start your work on this issue. Thanks
