### ISSUE TITLE
Add code quality tests

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#8]
#### Description of the problem

Currently there are no tests to check the quality of the code, example each file should end with new line, there should be no trailing white space.
A good place to add code quality tests will be, `pydatastructs.utils.tests.test_code_quality`.
#### References/Other comments
Refer, https://github.com/sympy/sympy/blob/master/sympy/utilities/tests/test_code_quality.py

**Comment by Kartikei-12** [comment]
#### Suggested external resource, Codacy

The Code quality check can be automated with [Codacy](codacy.com), without any explicit code in the repo.

Example reference [Kartikei-12/Pyrunc/](https://github.com/Kartikei-12/Pyrunc)

**Comment by czgdp1807** [comment]
Thanks for the idea. AFAICFO, I think Codacy needs to be installed and then we need to update `.travis.yml`. Am I right?

**Comment by Kartikei-12** [comment]
No Codacy installation is not required, and provides code quality measures directly in browser, an can be configured in the same way.
You just need to login with github and turn on repo monitoring.
Also it provided badge which can be added in README

**Comment by czgdp1807** [comment]
Thanks for the clarification. I will take a look into it.

**Comment by npalladium** [comment]
You could also look into setting up `black` and running it on every commit with git hooks. `pre-commit` might make setting the git hook up easier.

**Comment by czgdp1807** [comment]
We will add our own tests in the root directory. 
A file, `test_code_quality.py` will have functions for testing various issues with code like trailing whitespace, no newline at the end of the file, more than one new line at the end of the line, and much more. Any new quality parameter can be tested by adding a new function for it.

**Comment by npalladium** [comment]
Can you provide a list of parameters you wish to test at the moment?

**Comment by czgdp1807** [comment]
Currently, we need tests for trailing white spaces and new line issues at the end of the file.

**Comment by npalladium** [comment]
These seem to be more code style tests than code quality. `black` actual fixes the EOF empty line issue and enforces consistent formatting. Afaik, while it currently doesn't fix trailing whitespaces, there is an open issue to do the same. Could you look into it even if you have a separate code quality/style test module? 
Likewise using `flake8` also might be helpful. 
Again, I might be speaking without exact knowledge of the situation. Is there any reason not to use them? 
Kinda unrelated, but are there any thoughts of introducing type annotation?
