### ISSUE TITLE
Customised deepcopy for pydatastructs

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#90]
#### Description of the problem

Currently `copy.deepcopy` doesn't work for classes which inherit other classes. So, to fix this we will be needing our own `deepcopy` function. It should be added in `utils.misc_util`.

#### References/Other comments
https://github.com/codezonediitj/pydatastructs/issues/22

**Comment by prshnt19** [comment]
I would like to work on this issue. Is it available?

**Comment by czgdp1807** [comment]
In some cases where the object stored in the queue is of a user defined class like `Node` and its subclass' objects. Try using in segment trees.

**Comment by czgdp1807** [comment]
This isn't of much use as in my opinion, we can use the inbuilt implementation of simple data structures and focus on less commonly available implementation basically the graph algorithms and parallel implementations of simple algorithms. 
Closing.

**Comment by czgdp1807** [comment]
Though adding simple data structures is still welcome though it won't be used elsewhere in the package unless they are theoretically more efficient than the inbuilt implementations like `DynamicOneDimensionalArray` is better than the `list` when it comes to delete operation.
