### ISSUE TITLE
[Feature] Making the tool closer to other competitive languages

### ISSUE THREAD

**Issue by UmashankarTriforce** [codezonediitj/pydatastructs#94]
This tool can have additional features that make it more closer to preferred competitive coding programming languages like C++. I would like to add the following features: 
- [ ] Add datatype

**Comment by czgdp1807** [comment]
IMO, `STL` is very different from what we want to build.
Regarding the others, I  think you can start with static typing using `mypy`. It will be good to have it. May be, pick one module like `miscellaneous_data_types` and describe your approach on how will you change the APIs and the implementation in the comments below.
I am not in favor of using `Cython` as it will lead to mixing of two languages which will make the code difficult to maintain. Currently our plan is to use, `Boost.Python` and generate Python wrappers for the C++ backend. But that will happen once the Software design becomes stabilized may be after few releases.

**Comment by czgdp1807** [comment]
Let's see what others have to say, ping @codezonediitj/gssoc2020 @codezonediitj/maintainers

**Comment by UmashankarTriforce** [comment]
Alright let's align with the roadmap of this project and drop support for STL. 
Well as for the part of using `Boost.Python` I think it should work out, but I guess starting the modification now would make sense because there's not much of code to rewrite. After a few stable releases, it'll become a nightmare to change the backend. So maybe we could define a template for writing code and make it normalized now as the tool is in its early development stages

**Comment by UmashankarTriforce** [comment]
Alright let's align with the roadmap of this project and drop support for STL. 
Well as for the part of using `Boost.Python` I think it should work out, but I guess starting the modification now would make sense because there's not much of code to rewrite. After a few stable releases, it'll become a nightmare to change the backend. So maybe we could define a template for writing code and make it normalized now as the tool is in its early development stages

**Comment by UmashankarTriforce** [comment]
Alright let's align with the roadmap of this project and drop support for STL. 
Well as for the part of using `Boost.Python` I think it should work out, but I guess starting the modification now would make sense because there's not much of code to rewrite. After a few stable releases, it'll become a nightmare to change the backend. So maybe we could define a template for writing code and make it normalized now as the tool is in its early development stages

**Comment by czgdp1807** [comment]
IMHO, including static typing would be good as it will avoid many checks using `isinstance` and will reduce unnecessary code.

**Comment by czgdp1807** [comment]
We are not planning to write C++ back end(design is not stable, so making changes will be difficult) right now, though a new issue specific for that purpose can be opened, which we will look at later.

**Comment by UmashankarTriforce** [comment]
Okay sure let's first get started with static typing

**Comment by robotjellyzone** [comment]
Hi @UmashankarTriforce are you still active here as I cannot see your progress?

**Comment by czgdp1807** [comment]
IMHO, as of now we don't need optimizations. The focus is right now working on design and prototyping as many algorithms as possible so that porting the code to C++ will be easy in future. Thanks for your contributions.
